# Place the OpenQuatt repository contents directly in the ESPHome config folder.
# Enable exactly one profile below.
substitutions:
  device_name: openquatt
  friendly_name: OpenQuatt
  openquatt_root: openquatt
  components_root: components

packages:
  openquatt: !include configs/heatpump_listener/single_wifi.yaml
  # openquatt: !include configs/heatpump_listener/duo_wifi.yaml
  # openquatt: !include configs/heatpump_controller_q/single_wifi.yaml
  # openquatt: !include configs/heatpump_controller_q/duo_wifi.yaml
  # openquatt: !include configs/heatpump_controller_q/single_eth.yaml
  # openquatt: !include configs/heatpump_controller_q/duo_eth.yaml
  # openquatt: !include configs/waveshare/single_wifi.yaml
  # openquatt: !include configs/waveshare/duo_wifi.yaml

esphome:
  build_path: build/${device_name}
