# ==============================================================================
# OpenQuatt - Remote Package Bootstrap (example)
# ==============================================================================
# Purpose:
# - Keep only host-specific settings local (API/OTA/WiFi/secrets).
# - Pull substitutions + package stack from GitHub.
#
# Notes:
# - Replace `@main` with a fixed tag/commit in production.
# - This file is an example template; copy/rename for your own environment.
# ==============================================================================

packages:
  - github://jeroen85/OpenQuatt/openquatt/oq_substitutions.yaml@main
  - github://jeroen85/OpenQuatt/openquatt/oq_packages.yaml@main

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  project:
    name: ${project_name}
    version: ${project_version}
  min_version: 2025.11.0
  name_add_mac_suffix: false
  includes:
    - ${hp_perf_map_header}

esp32:
  board: ${esp_board}
  flash_size: ${esp_flash_size}
  variant: ${esp_variant}
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      COMPILER_OPTIMIZATION_SIZE: y
      CONFIG_BT_ENABLED: n

logger:
  level: DEBUG
  baud_rate: 0
  runtime_tag_levels: true

api:
  encryption:
    key: !secret api_key
  reboot_timeout: 0s

ota:
  platform: esphome
  password: !secret ota_password

wifi:
  manual_ip:
    gateway: !secret wifi_gateway
    subnet: !secret wifi_subnet
    static_ip: !secret ip_openquatt
    dns1: 8.8.8.8
    dns2: 1.1.1.1
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
  fast_connect: true
  min_auth_mode: wpa2
  ap:
    ssid: "OpenQuatt"
    password: "openquatt"
