# ==============================================================================
# OpenQuatt - Legacy Single Base Alias
# ==============================================================================
# Backward-compatible alias; prefer openquatt_base.yaml + setup profile include.
# ==============================================================================

substitutions: !include openquatt/profiles/oq_substitutions_setup_single.yaml

packages:
  openquatt_setup_packages: !include openquatt/oq_packages_single.yaml
  openquatt_base: !include openquatt_base.yaml
