# ==============================================================================
# OpenQuatt – openquatt.yaml
# Version: v0.12.1
#
# Purpose:
# - Top-level ESPHome config and package includes.
# - Keeps boot/runtime services and shared diagnostics in one place.
# ==============================================================================

# ==============================================================================
# SUBSTITUTIONS
# ==============================================================================
substitutions: !include openquatt/oq_substitutions.yaml

# ==============================================================================
# PACKAGES
# ==============================================================================
packages: !include openquatt/oq_packages.yaml

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  project:
    name: ${project_name}
    version: ${project_version}
  min_version: 2025.11.0
  name_add_mac_suffix: false
  includes:
    - openquatt/includes/hp_perf_map.h
  on_boot:
    priority: -100
    then:
      - text_sensor.template.publish:
          id: oq_project_version_text
          state: "${project_version}"

esp32:
  board: ${esp_board}
  flash_size: ${esp_flash_size}
  variant: ${esp_variant}
  framework:
    type: esp-idf
    version: recommended
    ## Custom sdkconfig options
    sdkconfig_options:
      COMPILER_OPTIMIZATION_SIZE: y
      CONFIG_BT_ENABLED: n

# Enable logging
logger:
  level: DEBUG
  baud_rate: 0
  runtime_tag_levels: true

# ==============================================================================
# NETWORK
# ==============================================================================
wifi:
  manual_ip:
    gateway: !secret wifi_gateway
    subnet: !secret wifi_subnet
    static_ip: !secret ip_openquatt
    dns1: 8.8.8.8
    dns2: 1.1.1.1
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
  fast_connect: true
  min_auth_mode: wpa2
  ap:
    ssid: "OpenQuatt"
    password: "openquatt"
