# ==============================================================================
# OpenQuatt - Main Config (Single setup, Heatpump Listener)
# ==============================================================================
substitutions:
  <<: !include openquatt/oq_substitutions_common.yaml
  system_setup: "single"
  release_manifest_url: "https://github.com/jeroen85/OpenQuatt/releases/latest/download/openquatt-single.manifest.json"
  oq_expr_hp2_outside_c: "NAN"
  oq_expr_hp2_flow_lph: "NAN"
  oq_expr_supply_fallback_c: "id(hp1_water_out_temp).state"
  oq_expr_boiler_upstream_outlet_c: "id(hp1_water_out_temp).state"
  oq_expr_hp2_working_mode: "NAN"
  oq_expr_hp2_last_applied_level: "0.0f"
  oq_expr_hp2_power_w: "NAN"
  oq_expr_hp2_heat_w: "NAN"
  oq_expr_hp2_runtime_min: "NAN"
  oq_stmt_hp2_runtime_reset: ""
  oq_stmt_hp2_low_noise_call: ""
  oq_stmt_hp2_pump_mode_call: ""
  oq_stmt_hp2_pump_pwm_call: ""

packages:
  openquatt_hw_profile: !include openquatt/profiles/oq_substitutions_heatpump_listener.yaml
  openquatt_base: !include openquatt_base_single.yaml
