# ==============================================================================
# OpenQuatt - Main Config (Waveshare ESP32-S3-Relay-1CH)
# ==============================================================================
substitutions: !include openquatt/oq_substitutions_common.yaml

packages:
  openquatt_hw_profile: !include openquatt/profiles/oq_substitutions_waveshare.yaml
  openquatt_base: !include openquatt_base.yaml
