# ==============================================================================
# OpenQuatt – openquatt.yaml
# Version: v0.12.1
#
# Purpose:
# - Top-level ESPHome config and package includes.
# - Runtime services and shared diagnostics are loaded via `oq_common` package.
# ==============================================================================

# ==============================================================================
# SUBSTITUTIONS
# ==============================================================================
substitutions: !include openquatt/oq_substitutions.yaml

# ==============================================================================
# PACKAGES
# ==============================================================================
packages: !include openquatt/oq_packages.yaml

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  project:
    name: ${project_name}
    version: ${project_version}
  min_version: 2025.11.0
  name_add_mac_suffix: false
  includes:
    - ${hp_perf_map_header}
  on_boot:
    priority: -100
    then:
      - text_sensor.template.publish:
          id: oq_project_version_text
          state: "${project_version}"

esp32:
  board: ${esp_board}
  flash_size: ${esp_flash_size}
  variant: ${esp_variant}
  framework:
    type: esp-idf
    version: recommended
    ## Custom sdkconfig options
    sdkconfig_options:
      COMPILER_OPTIMIZATION_SIZE: y
      CONFIG_BT_ENABLED: n
