const LOGO_MARKUP = `
    <svg class="oq-helper-logo-mark" role="img" aria-label="OpenQuatt logo" xmlns="http://www.w3.org/2000/svg" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;stroke-linejoin:round;stroke-miterlimit:2" viewBox="0 0 2680 900"><path d="M342.5 34.5a250 250 0 0 0 9 30q3.989 10.461 8 21 .486 7.441 5 13a939 939 0 0 0 52.5 110 2240 2240 0 0 0 60 96 5301 5301 0 0 1 69 102 417.3 417.3 0 0 1 33.5 64q.078 4.27 3 7 20.139 43.56 22.5 92a483 483 0 0 1-.5 49q-1.838 7.185-2 15-2.427 4.007-2 9l-2 11q-2.361 2.403-2 6v2q-3.93 5.764-5 13a361.4 361.4 0 0 1-25 51q-4.657 4.162-7 10-68.629 88.06-179 104a852 852 0 0 0-35 3q-16.507.25-33-.5-2.822-.297-5-1.5-9.157-2.244-19-2h-2q-7.544-2.872-16-3-113.521-21.405-172.5-121-43.368-84.229-27-178 7.821-43.96 27-84a586 586 0 0 1 33-56 5116 5116 0 0 0 130-196q21.751-40.5 42-82a2875 2875 0 0 1 20-49 273 273 0 0 0 11-35 59 59 0 0 1 5-9 29.8 29.8 0 0 1 3.5 9" style="fill:#204b96"/><path d="M342.5 34.5q6.278 14.341 9 30a250 250 0 0 1-9-30" style="fill:#6386b9"/><path d="M359.5 85.5q3.351 6.034 5 13-4.514-5.559-5-13" style="fill:#6486b9"/><path d="M342.5 119.5a571 571 0 0 1 14 40q.764 7.805 5 14v1q-.135 3.978 2 7a31.7 31.7 0 0 1 2 6q-.135 3.978 2 7-.135 3.978 2 7-.135 3.978 2 7-.135 3.978 2 7 8.966 31.83 13 65a1521 1521 0 0 0 4.5 49q.75 18.493.5 37v3q-1.152 1.144-1.5 3a919 919 0 0 0-3.5 30 85.4 85.4 0 0 0-1.5 13q26.267-39.549 29.5-87 .999-7.984 1-16.5.29-12.09-2-23.5a12.9 12.9 0 0 1 .5-5 56.1 56.1 0 0 1 10.5 17q-.11 2.29 2 3a1350 1350 0 0 1 17 37q-.501 4.486 3 7 4.654 9.453 7 20-.135 3.978 2 7-.135 3.978 2 7 3.267 9.564 4 20-.367 8.376 2 16 2.406 100.067-83 152-1.393-1.783-1-4 2.31-6.847 2-14.5.012-12.645-3-24.5.31-4.493-2-8-7.76-31.019-27.5-56-35.843 63.187-56 133l-3 5q-31.104 11.837-64.5 15.5a356 356 0 0 1-31 2.5q-18.405-58.648-2.5-118a202.4 202.4 0 0 1 17-39q45.29-69.55 83-144 28.532-61.85 40.5-129 6.37-24.912 7-51a167 167 0 0 0 3-18" style="fill:#eb8832"/><path d="M342.5 119.5a167 167 0 0 1-3 18 83.7 83.7 0 0 1 2-19q.91.186 1 1" style="fill:#575c6a"/><path d="M356.5 159.5a86.7 86.7 0 0 1 5 14q-4.236-6.195-5-14" style="fill:#a57341"/><path d="M361.5 174.5q2.135 3.022 2 7-2.135-3.022-2-7" style="fill:#9f7144"/><path d="M339.5 137.5q-.63 26.088-7 51a1077 1077 0 0 0 7-51" style="fill:#445877"/><path d="M365.5 187.5q2.135 3.022 2 7-2.135-3.022-2-7M367.5 194.5q2.135 3.022 2 7-2.135-3.022-2-7M369.5 201.5q2.135 3.022 2 7-2.135-3.022-2-7" style="fill:#a07241"/><path d="M371.5 208.5q2.135 3.022 2 7-2.135-3.022-2-7" style="fill:#9f7241"/><path d="M386.5 280.5a2229 2229 0 0 1 5.5 43q1.241 21.759-.5 43 .25-18.507-.5-37a1521 1521 0 0 1-4.5-49" style="fill:#987048"/><path d="M424.5 300.5q2.11.71 2 3-2.11-.71-2-3" style="fill:#746657"/><path d="M413.5 288.5q2.29 11.41 2 23.5-.001 8.516-1 16.5a601 601 0 0 0-1-40" style="fill:#485a73"/><path d="M443.5 340.5q2.347 3.014 3 7-3.501-2.514-3-7" style="fill:#a37144"/><path d="M453.5 367.5q2.135 3.022 2 7-2.135-3.022-2-7" style="fill:#9a6f46"/><path d="M455.5 374.5q2.135 3.022 2 7-2.135-3.022-2-7" style="fill:#926e47"/><path d="M391.5 369.5a317 317 0 0 1-5 33 919 919 0 0 1 3.5-30q.348-1.856 1.5-3" style="fill:#ac753c"/><path d="M461.5 401.5q2.186 7.647 2 16-2.367-7.624-2-16" style="fill:#a2733e"/><path d="M770.5 570.5a399 399 0 0 1 2-36q17.486-55.719 75-68.5 49.058-9.816 96 7 58.332 28.392 53.5 93.5-5.29 63.812-66.5 83.5-48.666 11.477-97-1-56.79-19.032-63-78.5m101-71q-31.006 3.518-48 30-9.226 23.782-4.5 49 12.264 35.252 49.5 39.5a194.4 194.4 0 0 0 37-1q15.804-4.398 28-15 21.365-23.762 15.5-55.5-4.6-23.892-24.5-37.5-25.143-11.653-53-9.5" style="fill:#3a89f3"/><path d="M1730.5 462.5q54.855-7.164 99 25.5c25.1 22.952 34.93 51.452 29.5 85.5q-5.445 28.14-25.5 48.5a215 215 0 0 0 32 24c.46.414.79.914 1 1.5a149.5 149.5 0 0 1-36.5 20l-3.5-.5a188.7 188.7 0 0 0-30-21.5c-32.01 10.572-64.34 11.739-97 3.5q-63.69-21.966-66-89.5 1.605-68.33 66-90.5c10.23-3.279 20.57-5.446 31-6.5m6 38c-2.47.817-5.14 1.317-8 1.5-20.21 4.676-34.38 16.51-42.5 35.5-8.24 27.209-2.08 50.375 18.5 69.5 19.63 11.699 40.3 13.699 62 6 .46-.414.79-.914 1-1.5-6.67-8.333-13.33-16.667-20-25a118 118 0 0 1 29-1.5c6.69 1.517 12.36 4.85 17 10 1.33.667 2.67.667 4 0 5.51-5.845 9.34-12.679 11.5-20.5 7.34-26.312.18-47.478-21.5-63.5q-23.79-12.921-51-10.5" style="fill:#ed8933"/><path d="M1567.5 469.5v-1h46c.32 6.854-.01 13.521-1 20v-19z" style="fill:#96c5f4"/><path d="M2250.5 648.5a326 326 0 0 0-14-37h-88a1243 1243 0 0 1-16 38.5c-16.66.5-33.33.667-50 .5a193 193 0 0 1 6.5-18 18553 18553 0 0 0 72-161c.83-.833 1.67-1.667 2.5-2.5q27-1 54 0c1.93.251 3.77.751 5.5 1.5q39.6 90.064 79.5 180c-17.57.631-34.9-.036-52-2m-59-142a1039 1039 0 0 1-23.5 57 130 130 0 0 0-4.5 15c19.68.333 39.34 0 59-1a1621 1621 0 0 1-27.5-66c-.9-1.931-2.07-3.597-3.5-5" style="fill:#ed8a33"/><path d="M2485.5 469.5v-1h180v37h-68c22.16-.997 44.49-1.331 67-1v-35z" style="fill:#eea659"/><path d="M1140.5 469.5c48.87 4.374 71.71 31.041 68.5 80-5.61 24.948-20.45 41.781-44.5 50.5a143 143 0 0 1-32 5c-20.66.5-41.33.667-62 .5-1 14.824-1.33 29.824-1 45h-43v-181zm-70 99c17.5 1.162 35.16 1.329 53 .5 2.54-.186 4.87-.686 7-1.5q19.125.322 28.5-16c8.31-25.692-.85-40.859-27.5-45.5-20.33-.5-40.66-.667-61-.5z" style="fill:#3989f3"/><path d="M1280.5 592.5c-.99 7.148-1.32 14.481-1 22h112v36c-51.88.655-103.55-.011-155-2a4879 4879 0 0 1-.5-165q.255-7.053 1.5-14 76.44-1.493 153-1v37h-111v38h102v34h-101z" style="fill:#3b8af3"/><path d="M1565.5 588.5q.42 1.184 1.5 2c.5-40.332.67-80.665.5-121h45v42c-1 46.164-1.33 92.497-1 139h-49a281 281 0 0 1-15.5-18 5912 5912 0 0 0-80-103c-.5 40.332-.67 80.665-.5 121h-43c.24-1.291-.1-2.291-1-3v-179c16.36-.283 32.69.217 49 1.5 31.55 39.375 62.88 78.875 94 118.5" style="fill:#3889f3"/><path d="M1567.5 468.5v1c.17 40.335 0 80.668-.5 121q-1.08-.816-1.5-2c.67-40 1.33-80 2-120" style="fill:#cfe7f9"/><path d="M1930.5 469.5a6522 6522 0 0 1 1.5 114c3.1 19.099 14.27 30.266 33.5 33.5 11.47 1.124 22.8.457 34-2 17.01-7.195 25.68-20.028 26-38.5 1-35.496 1.33-71.163 1-107h46v116q-10.38 61.13-72 68.5c-16.67.667-33.33.667-50 0q-58.77-9.515-66-68.5v-116z" style="fill:#ed8933"/><path d="M2072.5 585.5v-116h-46c.33 35.837 0 71.504-1 107v-108h48c.33 39.17 0 78.17-1 117" style="fill:#f1bd83"/><path d="M2461.5 468.5c1.42.951 3.09 1.284 5 1v35q-36.255-.497-72 1v145h-46v-8c1-45.83 1.33-91.83 1-138h-67v-35c59.64-.985 119.31-1.318 179-1M2485.5 469.5h179v35c-22.51-.331-44.84.003-67 1v145h-48v-145c-21.16-.997-42.49-1.331-64-1z" style="fill:#ed8932"/><path d="M579.5 470.5q2.348 3.014 3 7-2.922-2.73-3-7" style="fill:#7393c0"/><path d="M2282.5 469.5v35h67c.33 46.17 0 92.17-1 138v-137h-67c-.33-12.178 0-24.178 1-36" style="fill:#f2bd80"/><path d="M2461.5 468.5h6v37h-73q35.745-1.497 72-1v-35c-1.91.284-3.58-.049-5-1" style="fill:#f2bd82"/><path d="M2485.5 468.5v36c21.51-.331 42.84.003 64 1h-65c-.33-12.511 0-24.845 1-37" style="fill:#f2be84"/><path d="M1930.5 469.5h-46v116c-1-38.83-1.33-77.83-1-117 15.84-.33 31.51.004 47 1" style="fill:#ed9e49"/><path d="M376.5 518.5q2.31 3.507 2 8-1.902-3.608-2-8" style="fill:#575e68"/><path d="M378.5 526.5q3.012 11.855 3 24.5.31 7.653-2 14.5a544 544 0 0 0-1-39" style="fill:#555a71"/><path d="M772.5 534.5a399 399 0 0 0-2 36q-1.735-12.235-.5-25 .628-5.838 2.5-11" style="fill:#85b9f5"/><path d="M557.5 586.5q.837 1.935 3 2.5-56.438-5.331-112 6a1117 1117 0 0 0-43 12 2536 2536 0 0 1-107 37 412 412 0 0 1-76 13q-47.99 3.102-91-18a620 620 0 0 1-24-16.5q-3.118-9.6-2.5-20a345 345 0 0 0 36.5 21.5 194.3 194.3 0 0 0 42 9.5q44.101 4.2 87-7a550 550 0 0 0 32-7.5 1150 1150 0 0 1 96-31 342 342 0 0 1 82.5-11.5q39.153-1.598 76.5 10" style="fill:#81cbf2"/><path d="M557.5 586.5a248 248 0 0 0 15 4q-12.054 137.357-138 193.5-104.056 39.986-207-2-100.8-48.767-120-159.5a620 620 0 0 0 24 16.5q43.01 21.102 91 18a412 412 0 0 0 76-13 2536 2536 0 0 0 107-37 1117 1117 0 0 1 43-12q55.562-11.331 112-6-2.163-.565-3-2.5" style="fill:#3888f2"/><path d="M1280.5 592.5v21h89v1h-90c-.32-7.519.01-14.852 1-22" style="fill:#c9e0f8"/><path d="M604.5 618.5q.297 7.875-2 15 .162-7.815 2-15" style="fill:#a6bbd7"/><path d="M270.5 626.5q-42.899 11.2-87 7a659 659 0 0 0 53-1.5 1796 1796 0 0 1 34-5.5" style="fill:#3a6fb0"/><path d="M602.5 633.5q.427 4.993-2 9-.427-4.993 2-9" style="fill:#839fc7"/><path d="M1369.5 614.5v-1h23v38h-156v-3a3024 3024 0 0 0 155 2v-36z" style="fill:#76b1f3"/><path d="M1422.5 647.5c.9.709 1.24 1.709 1 3h43a485 485 0 0 1-44 1z" style="fill:#98c7f8"/><path d="M1612.5 511.5v140c-16.84.33-33.51-.003-50-1h49c-.33-46.503 0-92.836 1-139" style="fill:#7bb4f4"/><path d="M2394.5 505.5h1v146c-15.84.33-31.51-.004-47-1h46z" style="fill:#f6d4ac"/><path d="M598.5 653.5q.361 3.597-2 6-.361-3.597 2-6" style="fill:#8fa9cb"/><path d="M596.5 661.5q-1.649 6.966-5 13 1.07-7.236 5-13" style="fill:#7294c1"/><path d="M566.5 725.5q-2.343 5.838-7 10 2.343-5.838 7-10" style="fill:#a3b9d4"/><path d="M270.5 835.5q8.456.128 16 3-8.341-.684-16-3" style="fill:#557cb2"/><path d="M288.5 838.5q9.843-.244 19 2-9.825.069-19-2" style="fill:#597eb4"/><path d="M380.5 839.5q-17.097 3.54-35 3a852 852 0 0 1 35-3" style="fill:#7d9ac4"/></svg>
  `;
  const FIRMWARE_RELEASE_URLS = {
    main: "https://github.com/jeroen85/OpenQuatt/releases/latest",
    dev: "https://github.com/jeroen85/OpenQuatt/releases/tag/dev-latest",
  };
  const OFFICIAL_ESPHOME_UI_URL = "https://oi.esphome.io/v3/www.js";
  const ENTITY_REFRESH_CONCURRENCY = 2;
  const FAST_VIEW_ENTITY_REFRESH_CONCURRENCY = 4;
  const TREND_HISTORY_REFRESH_INTERVAL_MS = 60000;
  const STRATEGY_OPTION_POWER_HOUSE = "Power House";
  const STRATEGY_OPTION_CURVE = "Water Temperature Control (heating curve)";

  const QUICK_STEPS = [
    {
      id: "generation",
      kicker: "Stap 1",
      title: "Kies je Quatt Hybrid",
      copy: "Geef hier aan welke Quatt Hybrid je hebt. Dan zet OpenQuatt de juiste regeling klaar.",
      fields: [
        {
          title: "Quatt Hybrid-versie",
          copy: "Kies de versie die bij jouw Quatt hoort.",
        },
      ],
    },
    {
      id: "flow-source",
      kicker: "Stap 2",
      title: "Flowmeting configureren",
      copy: "Controleer en activeer de flowbron die bij jouw Quatt-versie en controller hoort.",
      fields: [
        {
          title: "Flowbron",
          copy: "De Quatt-versie en het hardwareprofiel bepalen automatisch welke flowbron OpenQuatt moet gebruiken.",
        },
      ],
    },
    {
      id: "thermostat-source",
      kicker: "Stap 3",
      title: "Thermostaatgegevens configureren",
      copy: "Leg vast waar OpenQuatt de kamertemperatuur en het kamer-setpoint samen vandaan haalt.",
      fields: [
        {
          title: "Thermostaatbron",
          copy: "Q-edition gebruikt OpenTherm. Listener en Waveshare gebruiken CiC of Home Assistant.",
        },
      ],
    },
    {
      id: "boiler",
      kicker: "Stap 4",
      title: "CV-ketel of boiler",
      copy: "Geef aan of OpenQuatt ondersteuning via een CV-ketel of boiler mag gebruiken.",
      optionalEntity: "boilerCvAssistEnabled",
      fields: [
        {
          title: "CV-ketel / boiler aanwezig",
          copy: "Kies of er ondersteuning beschikbaar is en vul eventueel het vermogen in.",
        },
      ],
    },
    {
      id: "strategy",
      kicker: "Stap 5",
      title: "Kies de verwarmingsstrategie",
      copy: "Kies hier hoe OpenQuatt je verwarming regelt. Daarna lopen we samen de belangrijkste instellingen langs.",
      fields: [
        {
          title: "Verwarmingsstrategie",
          copy: "Kies of OpenQuatt automatisch op je woning reageert, of werkt met een vaste stooklijn.",
        },
      ],
    },
    {
      id: "heating",
      kicker: "Stap 6",
      title: "Werk de regeling uit",
      copy: "Stel nu de gekozen regeling verder in. De inhoud hieronder past zich aan aan je keuze.",
      fields: [
        {
          title: "Instellingen voor jouw regeling",
          copy: "Je ziet hier alleen de instellingen die echt nodig zijn voor de gekozen regeling.",
        },
      ],
    },
    {
      id: "flow",
      kicker: "Stap 7",
      title: "Flowregeling en afstelling",
      copy: "Leg daarna vast hoe de pomp geregeld moet worden en welke waarden daarbij horen. De autotune staat later onder Instellingen → Installatie → Service & commissioning.",
      fields: [
        {
          title: "Flowregeling en tuning",
          copy: "Kies of OpenQuatt de pomp automatisch regelt, of dat je zelf een vaste pompstand instelt. Stel hier ook de flow-instellingen in.",
        },
      ],
    },
    {
      id: "water",
      kicker: "Stap 8",
      title: "Watertemperatuur beveiligen",
      copy: "Controleer de normale bovengrens en de tripgrens voor het watercircuit.",
      fields: [
        {
          title: "Watertemperatuur",
          copy: "Met deze grenzen voorkom je dat de watertemperatuur te hoog oploopt.",
        },
      ],
    },
    {
      id: "silent",
      kicker: "Stap 9",
      title: "Stille uren en niveaus",
      copy: "Stel daarna het stille venster en de compressorlimieten voor dag en nacht in.",
      fields: [
        {
          title: "Stille uren",
          copy: "Hier bepaal je wanneer het systeem rustiger moet werken.",
        },
      ],
    },
    {
      id: "confirm",
      kicker: "Stap 10",
      title: "Bevestigen en afronden",
      copy: "Controleer nog één keer je keuzes. Met afronden markeer je Quick Start als voltooid.",
      fields: [
        {
          title: "Afronden",
          copy: "Je instellingen zijn al opgeslagen. Deze stap markeert alleen dat Quick Start klaar is.",
        },
      ],
    },
  ];

  const ODU_RUNTIME_FREQUENCY_HP_IDS = [1, 2];
  const ODU_RUNTIME_FREQUENCY_LEVELS = Array.from({ length: 11 }, (_item, index) => index);
  const ODU_RUNTIME_FREQUENCY_MODES = ["cooling", "heating"];

  function getOduRuntimeFrequencyModeLabel(mode) {
    return mode === "cooling" ? "cooling" : "heating";
  }

  function getOduRuntimeFrequencyModeKey(mode) {
    return mode === "cooling" ? "Cooling" : "Heating";
  }

  function getOduRuntimeFrequencyValueKey(hpIndex, mode, level) {
    return `hp${hpIndex}OduRuntime${getOduRuntimeFrequencyModeKey(mode)}F${level}`;
  }

  function getOduRuntimeFrequencyControlKey(hpIndex, suffix) {
    return `hp${hpIndex}OduRuntimeFrequency${suffix}`;
  }

  function getOduRuntimeFrequencyHpKeys(hpIndex) {
    return [
      getOduRuntimeFrequencyControlKey(hpIndex, "Enable"),
      getOduRuntimeFrequencyControlKey(hpIndex, "Load"),
      getOduRuntimeFrequencyControlKey(hpIndex, "Apply"),
      getOduRuntimeFrequencyControlKey(hpIndex, "Status"),
      ...ODU_RUNTIME_FREQUENCY_MODES.flatMap((mode) => (
        ODU_RUNTIME_FREQUENCY_LEVELS.map((level) => getOduRuntimeFrequencyValueKey(hpIndex, mode, level))
      )),
    ];
  }

  function getOduRuntimeFrequencyButtonHp(key) {
    const match = String(key || "").match(/^hp([12])OduRuntimeFrequency(?:Load|Apply)$/);
    return match ? Number(match[1]) : 0;
  }

  const ODU_RUNTIME_FREQUENCY_KEYS = ODU_RUNTIME_FREQUENCY_HP_IDS.flatMap(getOduRuntimeFrequencyHpKeys);
  const ODU_RUNTIME_FREQUENCY_BUTTON_KEYS = new Set(
    ODU_RUNTIME_FREQUENCY_HP_IDS.flatMap((hpIndex) => [
      getOduRuntimeFrequencyControlKey(hpIndex, "Load"),
      getOduRuntimeFrequencyControlKey(hpIndex, "Apply"),
    ]),
  );

  const ENTITY_DEFS = {
    setupComplete: { domain: "binary_sensor", name: "Setup Complete", optional: true },
    status: { domain: "binary_sensor", name: "Status", optional: true },
    firmwareUpdate: { domain: "update", name: "Firmware Update", optional: true },
    firmwareUpdateChannel: { domain: "select", name: "Firmware Update Channel", optional: true },
    firmwareUpdateTarget: { domain: "select", name: "Firmware Update Target", optional: true },
    firmwareUpdateProgress: { domain: "sensor", name: "Firmware Update Progress", optional: true },
    firmwareUpdateStatus: { domain: "text_sensor", name: "Firmware Update Status", optional: true },
    firmwareTestOtaUrl: { domain: "text", name: "Firmware Test OTA URL", optional: true },
    firmwareTestOtaMd5Url: { domain: "text", name: "Firmware Test OTA MD5 URL", optional: true },
    checkFirmwareUpdates: { domain: "button", name: "Check Firmware Updates", optional: true },
    installFirmwareTestOta: { domain: "button", name: "Install Firmware Test OTA", optional: true },
    installFirmwareUpdateTarget: { domain: "button", name: "Install Firmware Update Target", optional: true },
    restartAction: { domain: "button", name: "Restart", optional: true },
    uptime: { domain: "sensor", name: "Uptime", optional: true },
    uptimeReadable: { domain: "text_sensor", name: "Uptime readable", optional: true },
    timeNowHhmm: { domain: "text_sensor", name: "Time now (HH:MM)", optional: true },
    timeValid: { domain: "binary_sensor", name: "Time valid", optional: true },
    ipAddress: { domain: "text_sensor", name: "IP Address", optional: true },
    wifiSsid: { domain: "text_sensor", name: "WiFi SSID", optional: true },
    projectVersionText: { domain: "text_sensor", name: "OpenQuatt Version", optional: true },
    releaseChannelText: { domain: "text_sensor", name: "OpenQuatt Release Channel", optional: true },
    installationTopology: { domain: "text_sensor", name: "OpenQuatt Installation Topology", optional: true },
    hardwareProfileText: { domain: "text_sensor", name: "OpenQuatt Hardware Profile", optional: true },
    connectionText: { domain: "text_sensor", name: "OpenQuatt Connection", optional: true },
    wifiSignal: { domain: "sensor", name: "WiFi Signal", optional: true },
    espInternalTemp: { domain: "sensor", name: "ESP Internal Temperature", optional: true },
    hpGeneration: { domain: "select", name: "Quatt Hybrid version" },
    strategy: { domain: "select", name: "Heating Control Mode" },
    openquattEnabled: { domain: "switch", name: "OpenQuatt Enabled", optional: true },
    boilerCvAssistEnabled: { domain: "switch", name: "Boiler assist enabled", optional: true },
    manualCoolingEnable: { domain: "switch", name: "Manual Cooling Enable", optional: true },
    cicCompatibilityMode: { domain: "switch", name: "CiC Compatibility Mode", optional: true },
    silentModeOverride: { domain: "select", name: "Silent Mode Override", optional: true },
    heatingEnableSelected: { domain: "binary_sensor", name: "Heating Enable (Selected)", optional: true },
    heatingEnableValid: { domain: "binary_sensor", name: "Heating Enable Valid", optional: true },
    heatingBlockedByThermostat: { domain: "binary_sensor", name: "Heating blocked by thermostat", optional: true },
    coolingEnableSelected: { domain: "binary_sensor", name: "Cooling Enable (Selected)", optional: true },
    coolingRequestActive: { domain: "binary_sensor", name: "Cooling Request Active", optional: true },
    coolingPermitted: { domain: "binary_sensor", name: "Cooling Permitted", optional: true },
    coolingBlockReason: { domain: "text_sensor", name: "Cooling Block Reason", optional: true },
    coolingGuardMode: { domain: "text_sensor", name: "Cooling Guard Mode", optional: true },
    coolingDewPointSelected: { domain: "sensor", name: "Cooling Dew Point (Selected)", optional: true },
    coolingMinimumSafeSupplyTemp: { domain: "sensor", name: "Cooling Minimum Safe Supply Temp", optional: true },
    coolingEffectiveMinSupplyTemp: { domain: "sensor", name: "Cooling Effective Minimum Supply Temp", optional: true },
    coolingFallbackNightMinOutdoorTemp: { domain: "sensor", name: "Cooling Fallback Night Minimum Outdoor Temp", optional: true },
    coolingFallbackMinSupplyTemp: { domain: "sensor", name: "Cooling Fallback Minimum Supply Temp", optional: true },
    coolingSupplyTarget: { domain: "sensor", name: "Cooling Supply Target", optional: true },
    coolingSupplyError: { domain: "sensor", name: "Cooling Supply Error", optional: true },
    coolingDemandRaw: { domain: "sensor", name: "Cooling Demand (raw)", optional: true },
    coolingBaseDemandRaw: { domain: "sensor", name: "Cooling base demand raw", optional: true },
    coolingLimitedDemand: { domain: "sensor", name: "Cooling limited demand", optional: true },
    coolingLimiterAllowedMax: { domain: "sensor", name: "Cooling limiter allowed max", optional: true },
    coolingBufferGapFiltered: { domain: "sensor", name: "Cooling buffer gap filtered", optional: true },
    coolingBufferGapRate: { domain: "sensor", name: "Cooling buffer gap rate", optional: true },
    coolingProjectedGap: { domain: "sensor", name: "Cooling projected gap", optional: true },
    coolingProjectionBrakeActive: { domain: "sensor", name: "Cooling projection brake active", optional: true },
    coolingDewGap: { domain: "sensor", name: "Cooling dew gap", optional: true },
    coolingStopBufferGap: { domain: "sensor", name: "Cooling stop buffer gap", optional: true },
    coolingLimiterReasonCode: { domain: "sensor", name: "Cooling limiter reason code", optional: true },
    coolingStopReasonCode: { domain: "sensor", name: "Cooling stop reason code", optional: true },
    coolingRequestReasonCode: { domain: "sensor", name: "Cooling request reason code", optional: true },
    coolingRequestHp1Level: { domain: "sensor", name: "Cooling request HP1 level", optional: true },
    coolingRequestHp2Level: { domain: "sensor", name: "Cooling request HP2 level", optional: true },
    coolingRequestOwnerHp: { domain: "sensor", name: "Cooling request owner HP", optional: true },
    coolingOwnerHp: { domain: "sensor", name: "Cooling owner HP", optional: true },
    coolingWaterCycleActive: { domain: "sensor", name: "Cooling water cycle active", optional: true },
    waterSupplySource: { domain: "select", name: "Water Supply Source", optional: true },
    flowSource: { domain: "select", name: "Flow Source", optional: true },
    qFlowSource: { domain: "select", name: "Q Flow Source", optional: true },
    outdoorUnitFlowMode: { domain: "select", name: "Outdoor Unit Flow Mode", optional: true },
    outsideTempSource: { domain: "select", name: "Outside Temperature Source", optional: true },
    roomTempSource: { domain: "select", name: "Room Temperature Source", optional: true },
    roomSetpointSource: { domain: "select", name: "Room Setpoint Source", optional: true },
    heatingEnableSource: { domain: "select", name: "Heating Enable Source", optional: true },
    coolingEnableSource: { domain: "select", name: "Cooling Enable Source", optional: true },
    localWaterSupplyTempSource: { domain: "select", name: "Local Water Supply Temp Source", optional: true },
    coolingMinimumSupplyTemp: { domain: "number", name: "Cooling Minimum Supply Temp", optional: true },
    coolingDemandMax: { domain: "number", name: "Cooling Demand Max", optional: true },
    coolingRestartDelta: { domain: "number", name: "Cooling Restart Delta", optional: true },
    coolingPidKp: { domain: "number", name: "Cooling PID Kp", optional: true },
    coolingPidKi: { domain: "number", name: "Cooling PID Ki", optional: true },
    coolingPidKd: { domain: "number", name: "Cooling PID Kd", optional: true },
    coolingSafetyMargin: { domain: "number", name: "Cooling Safety Margin", optional: true },
    coolingRequestOnDelta: { domain: "number", name: "Cooling Request On Delta", optional: true },
    coolingRequestOffDelta: { domain: "number", name: "Cooling Request Off Delta", optional: true },
    coolingWithoutDewPointMode: { domain: "select", name: "Cooling Without Dew Point", optional: true },
    flowControlMode: { domain: "select", name: "Flow Control Mode" },
    flowSetpoint: { domain: "number", name: "Flow Setpoint" },
    coolingFlowSetpoint: { domain: "number", name: "Cooling Flow Setpoint", optional: true },
    manualIpwm: { domain: "number", name: "Manual iPWM" },
    compressorStarts2hWarningLimit: { domain: "number", name: "Compressor starts 2h warning limit", optional: true },
    compressorStarts72hWarningLimit: { domain: "number", name: "Compressor starts 72h warning limit", optional: true },
    compressorCyclingWarning2h: { domain: "binary_sensor", name: "Compressor cycling warning 2h", optional: true },
    compressorCyclingWarning72h: { domain: "binary_sensor", name: "Compressor cycling warning 72h", optional: true },
    alternatingCompressorStartsWarning: { domain: "binary_sensor", name: "Alternating compressor starts warning", optional: true },
    compressorCyclingAlertLatched: { domain: "binary_sensor", name: "Compressor cycling alert latched", optional: true },
    compressorCyclingAlertAlternating: { domain: "binary_sensor", name: "Compressor cycling alert alternating", optional: true },
    compressorCyclingAlertFirstSeen: { domain: "sensor", name: "Compressor cycling alert first seen", optional: true },
    compressorCyclingAlertLastSeen: { domain: "sensor", name: "Compressor cycling alert last seen", optional: true },
    compressorCyclingAlertHp1Peak2h: { domain: "sensor", name: "Compressor cycling alert HP1 peak 2h", optional: true },
    compressorCyclingAlertHp1Peak72h: { domain: "sensor", name: "Compressor cycling alert HP1 peak 72h", optional: true },
    compressorCyclingAlertHp2Peak2h: { domain: "sensor", name: "Compressor cycling alert HP2 peak 2h", optional: true },
    compressorCyclingAlertHp2Peak72h: { domain: "sensor", name: "Compressor cycling alert HP2 peak 72h", optional: true },
    acknowledgeCompressorCyclingAlert: { domain: "button", name: "Acknowledge compressor cycling alert", optional: true },
    hp1CompressorStarts2h: { domain: "sensor", name: "HP1 - Compressor starts 2h", optional: true },
    hp1CompressorStarts6h: { domain: "sensor", name: "HP1 - Compressor starts 6h", optional: true },
    hp1CompressorStarts24h: { domain: "sensor", name: "HP1 - Compressor starts 24h", optional: true },
    hp1CompressorStarts72h: { domain: "sensor", name: "HP1 - Compressor starts 72h", optional: true },
    hp1CompressorLastStartAge: { domain: "sensor", name: "HP1 - Compressor last start age", optional: true },
    hp2CompressorStarts2h: { domain: "sensor", name: "HP2 - Compressor starts 2h", optional: true },
    hp2CompressorStarts6h: { domain: "sensor", name: "HP2 - Compressor starts 6h", optional: true },
    hp2CompressorStarts24h: { domain: "sensor", name: "HP2 - Compressor starts 24h", optional: true },
    hp2CompressorStarts72h: { domain: "sensor", name: "HP2 - Compressor starts 72h", optional: true },
    hp2CompressorLastStartAge: { domain: "sensor", name: "HP2 - Compressor last start age", optional: true },
    lowflowFaultActive: { domain: "binary_sensor", name: "Lowflow fault active", optional: true },
    flowMismatch: { domain: "binary_sensor", name: "Flow mismatch (HP1 vs HP2)", optional: true },
    cicPollingEnabled: { domain: "switch", name: "CIC - Enable polling", optional: true },
    cicFeedUrl: { domain: "text", name: "CIC - Feed URL", optional: true },
    cicWaterSupplyTemp: { domain: "sensor", name: "CIC - Water Supply Temp", optional: true },
    cicControlSetpoint: { domain: "sensor", name: "CIC - Control setpoint", optional: true },
    cicRoomSetpoint: { domain: "sensor", name: "CIC - Room setpoint", optional: true },
    cicRoomTemp: { domain: "sensor", name: "CIC - Room temperature", optional: true },
    cicFlowrate: { domain: "sensor", name: "CIC - Flowrate (filtered)", optional: true },
    cicLastSuccessAge: { domain: "sensor", name: "CIC - Last success age", optional: true },
    cicChEnabled: { domain: "binary_sensor", name: "CIC - CH enabled", optional: true },
    cicChEnableValid: { domain: "binary_sensor", name: "CIC - CH enable valid", optional: true },
    cicCoolingEnabled: { domain: "binary_sensor", name: "CIC - Cooling enabled", optional: true },
    cicJsonFeedOk: { domain: "binary_sensor", name: "CIC - JSON Feed OK", optional: true },
    cicDataStale: { domain: "binary_sensor", name: "CIC - Data stale", optional: true },
    otEnabled: { domain: "switch", name: "OpenTherm Enabled", optional: true },
    otThermostatChEnable: { domain: "binary_sensor", name: "OT - Thermostat CH Enable", optional: true },
    otThermostatStatusValid: { domain: "binary_sensor", name: "OT - Thermostat Status Valid", optional: true },
    otThermostatCoolingEnable: { domain: "binary_sensor", name: "OT - Thermostat Cooling Enable", optional: true },
    otLinkProblem: { domain: "binary_sensor", name: "OT - Link Problem", optional: true },
    otControlSetpoint: { domain: "sensor", name: "OT - Control Setpoint", optional: true },
    otRoomSetpoint: { domain: "sensor", name: "OT - Room Setpoint", optional: true },
    otRoomTemp: { domain: "sensor", name: "OT - Room Temperature", optional: true },
    flowKp: { domain: "number", name: "Flow PI Kp", optional: true },
    flowKi: { domain: "number", name: "Flow PI Ki", optional: true },
    boilerRatedHeatPower: { domain: "number", name: "Boiler rated heat power", optional: true },
    commissioningCm100Start: { domain: "button", name: "CM100 Start", optional: true },
    commissioningCm100Stop: { domain: "button", name: "CM100 Stop", optional: true },
    commissioningStatus: { domain: "text_sensor", name: "Commissioning status", optional: true },
    cm100Active: { domain: "binary_sensor", name: "CM100 active", optional: true },
    boilerPowerTestStart: { domain: "button", name: "Boiler Power Test Start", optional: true },
    boilerPowerTestAbort: { domain: "button", name: "Boiler Power Test Abort", optional: true },
    boilerPowerTestApply: { domain: "button", name: "Boiler Power Test Apply", optional: true },
    boilerPowerTestResult: { domain: "sensor", name: "Boiler power test result", optional: true },
    boilerPowerTestActive: { domain: "binary_sensor", name: "Boiler power test active", optional: true },
    boilerPowerTestStatus: { domain: "text_sensor", name: "Boiler power test status", optional: true },
    flowAutotuneStart: { domain: "button", name: "Flow Autotune Start", optional: true },
    flowAutotuneAbort: { domain: "button", name: "Flow Autotune Abort", optional: true },
    flowAutotuneApply: { domain: "button", name: "Apply Flow Autotune Kp-Ki", optional: true },
    flowAutotuneStatus: { domain: "text_sensor", name: "Flow Autotune status", optional: true },
    flowKpSuggested: { domain: "number", name: "Flow Autotune Kp suggested", optional: true },
    flowKiSuggested: { domain: "number", name: "Flow Autotune Ki suggested", optional: true },
    airPurgeStart: { domain: "button", name: "Air Purge Start", optional: true },
    airPurgeAbort: { domain: "button", name: "Air Purge Abort", optional: true },
    airPurgeReturnToAuto: { domain: "switch", name: "Air purge return to Auto", optional: true },
    airPurgeActive: { domain: "binary_sensor", name: "Air purge active", optional: true },
    airPurgeStatus: { domain: "text_sensor", name: "Air purge status", optional: true },
    airPurgeRemaining: { domain: "sensor", name: "Air purge remaining", optional: true },
    airPurgePhase: { domain: "sensor", name: "Air purge phase", optional: true },
    airPurgeTargetIpwm: { domain: "sensor", name: "Air purge target iPWM", optional: true },
    manualFlowStart: { domain: "button", name: "Manual Flow Start", optional: true },
    manualFlowAbort: { domain: "button", name: "Manual Flow Abort", optional: true },
    manualFlowApplyHeating: { domain: "button", name: "Apply Manual Flow To Heating", optional: true },
    manualFlowApplyCooling: { domain: "button", name: "Apply Manual Flow To Cooling", optional: true },
    manualFlowActive: { domain: "binary_sensor", name: "Manual flow active", optional: true },
    manualFlowStatus: { domain: "text_sensor", name: "Manual flow status", optional: true },
    manualFlowSetpoint: { domain: "number", name: "Manual flow service setpoint", optional: true },
    manualFlowTargetIpwm: { domain: "sensor", name: "Manual flow target iPWM", optional: true },
    quickFlowTest: { domain: "switch", name: "Quick flow test", optional: true },
    manualHpStart: { domain: "button", name: "Manual HP Start", optional: true },
    manualHpAbort: { domain: "button", name: "Manual HP Abort", optional: true },
    manualHpActive: { domain: "binary_sensor", name: "Manual HP active", optional: true },
    manualHpStatus: { domain: "text_sensor", name: "Manual HP status", optional: true },
    manualHpGuardStatus: { domain: "text_sensor", name: "Manual HP guard status", optional: true },
    manualHp1Mode: { domain: "select", name: "Manual HP1 service mode", optional: true },
    manualHp2Mode: { domain: "select", name: "Manual HP2 service mode", optional: true },
    manualHp1Level: { domain: "number", name: "Manual HP1 compressor level", optional: true },
    manualHp2Level: { domain: "number", name: "Manual HP2 compressor level", optional: true },
    hpWaterCalibrationStart: { domain: "button", name: "HP Water Calibration Start", optional: true },
    hpWaterCalibrationAbort: { domain: "button", name: "HP Water Calibration Abort", optional: true },
    hpWaterCalibrationApply: { domain: "button", name: "Apply HP Water Calibration Offsets", optional: true },
    hpWaterCalibrationActive: { domain: "binary_sensor", name: "HP water calibration active", optional: true },
    hpWaterCalibrationStatus: { domain: "text_sensor", name: "HP water calibration status", optional: true },
    hpWaterCalibrationRemaining: { domain: "sensor", name: "HP water calibration remaining", optional: true },
    hpWaterCalibrationPhase: { domain: "sensor", name: "HP water calibration phase", optional: true },
    hpWaterCalibrationSpread: { domain: "sensor", name: "HP water calibration spread", optional: true },
    hpWaterCalibrationSupplyDelta: { domain: "sensor", name: "HP water calibration supply delta", optional: true },
    hpWaterCalibrationStableProgress: { domain: "sensor", name: "HP water calibration stable window progress", optional: true },
    hpWaterCalibrationStableRequired: { domain: "sensor", name: "HP water calibration stable window required", optional: true },
    hpWaterCalibrationResultReference: { domain: "sensor", name: "HP water calibration result reference", optional: true },
    hpWaterCalibrationResultSpreadBefore: { domain: "sensor", name: "HP water calibration result spread before", optional: true },
    hpWaterCalibrationResultExpectedSpread: { domain: "sensor", name: "HP water calibration result expected spread", optional: true },
    hpWaterCalibrationResultHp1InRawAvg: { domain: "sensor", name: "HP water calibration result HP1 water in raw average", optional: true },
    hpWaterCalibrationResultHp1OutRawAvg: { domain: "sensor", name: "HP water calibration result HP1 water out raw average", optional: true },
    hpWaterCalibrationResultHp2InRawAvg: { domain: "sensor", name: "HP water calibration result HP2 water in raw average", optional: true },
    hpWaterCalibrationResultHp2OutRawAvg: { domain: "sensor", name: "HP water calibration result HP2 water out raw average", optional: true },
    hp1WaterInOffset: { domain: "number", name: "HP1 water in temperature offset", optional: true },
    hp1WaterOutOffset: { domain: "number", name: "HP1 water out temperature offset", optional: true },
    hp2WaterInOffset: { domain: "number", name: "HP2 water in temperature offset", optional: true },
    hp2WaterOutOffset: { domain: "number", name: "HP2 water out temperature offset", optional: true },
    hp1WaterInOffsetSuggested: { domain: "number", name: "HP calibration HP1 water in offset suggested", optional: true },
    hp1WaterOutOffsetSuggested: { domain: "number", name: "HP calibration HP1 water out offset suggested", optional: true },
    hp2WaterInOffsetSuggested: { domain: "number", name: "HP calibration HP2 water in offset suggested", optional: true },
    hp2WaterOutOffsetSuggested: { domain: "number", name: "HP calibration HP2 water out offset suggested", optional: true },
    controlModeLabel: { domain: "text_sensor", name: "Control Mode (Label)" },
    flowMode: { domain: "text_sensor", name: "Flow Mode" },
    dayMax: { domain: "number", name: "Day max level" },
    silentMax: { domain: "number", name: "Silent max level" },
    silentStartTime: { domain: "time", name: "Silent start time" },
    silentEndTime: { domain: "time", name: "Silent end time" },
    openquattResumeAt: { domain: "datetime", name: "OpenQuatt resume at", optional: true },
    maxWater: { domain: "number", name: "Maximum water temperature" },
    minRuntime: { domain: "number", name: "Minimum runtime" },
    totalPower: { domain: "sensor", name: "Total Power Input" },
    heatingPowerInput: { domain: "sensor", name: "Heating Power Input", optional: true },
    coolingPowerInput: { domain: "sensor", name: "Cooling Power Input", optional: true },
    totalCop: { domain: "sensor", name: "Total COP" },
    totalEer: { domain: "sensor", name: "Total EER", optional: true },
    totalHeat: { domain: "sensor", name: "Total Heat Power" },
    totalCoolingPower: { domain: "sensor", name: "Total Cooling Power", optional: true },
    boilerActive: { domain: "binary_sensor", name: "Boiler active", optional: true },
    boilerHeatPower: { domain: "sensor", name: "Boiler Heat Power", optional: true },
    systemHeatPower: { domain: "sensor", name: "System Heat Power", optional: true },
    flowSelected: { domain: "sensor", name: "Flow average (Selected)" },
    flowLocal: { domain: "sensor", name: "Flow average (local)", optional: true },
    controllerFlow: { domain: "sensor", name: "Controller Flow", optional: true },
    trendHistoryEnabled: { domain: "switch", name: "Trendopslag", optional: true },
    trendHistoryFlashEnabled: { domain: "switch", name: "Trendhistorie opslaan in flash", optional: true },
    webServerLogHistoryEnabled: { domain: "switch", name: "RAM log history", optional: true },
    debugLevel: { domain: "select", name: "Debug Level", optional: true },
    trendHistoryFlush: { domain: "button", name: "Trendhistorie nu opslaan", optional: true },
    trendHistoryFlashAvailable: { domain: "text_sensor", name: "Trendhistorie beschikbaar", optional: true },
    trendHistoryFlashOldest: { domain: "text_sensor", name: "Trendhistorie oudste punt", optional: true },
    trendHistoryFlashNewest: { domain: "text_sensor", name: "Trendhistorie nieuwste punt", optional: true },
    trendHistoryFlashLastFlush: { domain: "text_sensor", name: "Trendhistorie laatste opslag", optional: true },
    trendHistoryFlashSize: { domain: "sensor", name: "Trendhistorie grootte", optional: true },
    trendHistoryFlashWrites: { domain: "sensor", name: "Trendhistorie schrijfacties", optional: true },
    lifetimeEnergyHistoryEnabled: { domain: "switch", name: "Lifetime energiehistorie opslaan", optional: true },
    lifetimeEnergyHourRetention: { domain: "select", name: "Uurdetail bewaren", optional: true },
    lifetimeEnergyHistoryCapture: { domain: "button", name: "Lifetime energiehistorie nu opslaan", optional: true },
    lifetimeEnergyHistoryClear: { domain: "button", name: "Lifetime energiehistorie wissen", optional: true },
    lifetimeEnergyHistoryAvailable: { domain: "text_sensor", name: "Lifetime energiehistorie beschikbaar", optional: true },
    lifetimeEnergyHistoryOldest: { domain: "text_sensor", name: "Lifetime energiehistorie oudste dag", optional: true },
    lifetimeEnergyHistoryNewest: { domain: "text_sensor", name: "Lifetime energiehistorie nieuwste dag", optional: true },
    lifetimeEnergyHistoryLastWrite: { domain: "text_sensor", name: "Lifetime energiehistorie laatste opslag", optional: true },
    lifetimeEnergyHistorySize: { domain: "sensor", name: "Lifetime energiehistorie grootte", optional: true },
    lifetimeEnergyHistoryWrites: { domain: "sensor", name: "Lifetime energiehistorie schrijfacties", optional: true },
    electricalEnergyDaily: { domain: "sensor", name: "Electrical Energy Daily", optional: true },
    electricalEnergyCumulative: { domain: "sensor", name: "Electrical Energy Cumulative", optional: true },
    heatingElectricalEnergyDaily: { domain: "sensor", name: "Heating Electrical Energy Daily", optional: true },
    heatingElectricalEnergyCumulative: { domain: "sensor", name: "Heating Electrical Energy Cumulative", optional: true },
    coolingElectricalEnergyDaily: { domain: "sensor", name: "Cooling Electrical Energy Daily", optional: true },
    coolingElectricalEnergyCumulative: { domain: "sensor", name: "Cooling Electrical Energy Cumulative", optional: true },
    heatpumpThermalEnergyDaily: { domain: "sensor", name: "HeatPump Thermal Energy Daily", optional: true },
    heatpumpThermalEnergyCumulative: { domain: "sensor", name: "HeatPump Thermal Energy Cumulative", optional: true },
    heatpumpCoolingEnergyDaily: { domain: "sensor", name: "HeatPump Cooling Energy Daily", optional: true },
    heatpumpCoolingEnergyCumulative: { domain: "sensor", name: "HeatPump Cooling Energy Cumulative", optional: true },
    heatpumpCopDaily: { domain: "sensor", name: "HeatPump COP Daily", optional: true },
    heatpumpCopCumulative: { domain: "sensor", name: "HeatPump COP Cumulative", optional: true },
    heatpumpEerDaily: { domain: "sensor", name: "HeatPump EER Daily", optional: true },
    heatpumpEerCumulative: { domain: "sensor", name: "HeatPump EER Cumulative", optional: true },
    boilerThermalEnergyDaily: { domain: "sensor", name: "Boiler Thermal Energy Daily", optional: true },
    boilerThermalEnergyCumulative: { domain: "sensor", name: "Boiler Thermal Energy Cumulative", optional: true },
    systemThermalEnergyDaily: { domain: "sensor", name: "System Thermal Energy Daily", optional: true },
    systemThermalEnergyCumulative: { domain: "sensor", name: "System Thermal Energy Cumulative", optional: true },
    roomTemp: { domain: "sensor", name: "Room Temperature (Selected)" },
    roomSetpoint: { domain: "sensor", name: "Room Setpoint (Selected)" },
    supplyTemp: { domain: "sensor", name: "Water Supply Temp (Selected)" },
    outsideTempSelected: { domain: "sensor", name: "Outside Temperature (Selected)", optional: true },
    waterSupplyTempEsp: { domain: "sensor", name: "Water Supply Temp", optional: true },
    waterSupplyTempDs18b20: { domain: "sensor", name: "Water Supply Temp (DS18B20)", optional: true },
    outsideTempLocalAggregated: { domain: "sensor", name: "Outside Temperature (Local aggregated)", optional: true },
    outsideTempHa: { domain: "sensor", name: "HA - Outside Temperature", optional: true },
    waterSupplyTempHa: { domain: "sensor", name: "HA - Water Supply Temperature", optional: true },
    roomSetpointHa: { domain: "sensor", name: "HA - Thermostat Setpoint", optional: true },
    roomTempHa: { domain: "sensor", name: "HA - Thermostat Room Temperature", optional: true },
    heatingEnableHa: { domain: "binary_sensor", name: "HA - Heating Enable", optional: true },
    coolingEnableHa: { domain: "binary_sensor", name: "HA - Cooling Enable", optional: true },
    outsideTempHaValid: { domain: "binary_sensor", name: "HA - Outside Temperature Valid", optional: true },
    waterSupplyTempHaValid: { domain: "binary_sensor", name: "HA - Water Supply Temperature Valid", optional: true },
    roomSetpointHaValid: { domain: "binary_sensor", name: "HA - Room Setpoint Valid", optional: true },
    roomTempHaValid: { domain: "binary_sensor", name: "HA - Room Temperature Valid", optional: true },
    heatingEnableHaValid: { domain: "binary_sensor", name: "HA - Heating Enable Valid", optional: true },
    coolingEnableHaValid: { domain: "binary_sensor", name: "HA - Cooling Enable Valid", optional: true },
    roomTempEffectiveSource: { domain: "text_sensor", name: "Room Temperature Effective Source", optional: true },
    roomSetpointEffectiveSource: { domain: "text_sensor", name: "Room Setpoint Effective Source", optional: true },
    heatingEnableEffectiveSource: { domain: "text_sensor", name: "Heating Enable Effective Source", optional: true },
    coolingEnableEffectiveSource: { domain: "text_sensor", name: "Cooling Enable Effective Source", optional: true },
    curveSupplyTarget: { domain: "sensor", name: "Heating Curve Supply Target" },
    requestReason: { domain: "text_sensor", name: "Request Reason", optional: true },
    strategyActiveCode: { domain: "sensor", name: "Strategy active code", optional: true },
    strategyPhaseCode: { domain: "sensor", name: "Strategy phase code", optional: true },
    strategyRequestedPower: { domain: "sensor", name: "Strategy requested power", optional: true },
    strategySupplyTarget: { domain: "sensor", name: "Strategy supply target", optional: true },
    strategyWaterLimitFactor: { domain: "sensor", name: "Strategy water limit factor", optional: true },
    strategyRequestActive: { domain: "binary_sensor", name: "Strategy request active", optional: true },
    strategyWaterTripActive: { domain: "binary_sensor", name: "Strategy water trip active", optional: true },
    strategyWaterHardTripActive: { domain: "binary_sensor", name: "Strategy water hard trip active", optional: true },
    curveDemandEffective: { domain: "sensor", name: "Curve demand (effective)", optional: true },
    curveDemandDiscrete: { domain: "sensor", name: "Curve demand (discrete)", optional: true },
    curveDispatchTotalLevel: { domain: "sensor", name: "Curve dispatch total level", optional: true },
    curveTargetHp1Level: { domain: "sensor", name: "Curve target HP1 level", optional: true },
    curveTargetHp2Level: { domain: "sensor", name: "Curve target HP2 level", optional: true },
    curveRestartInhibit: { domain: "sensor", name: "Curve restart inhibit", optional: true },
    curvePhase: { domain: "text_sensor", name: "Curve Phase", optional: true },
    curveOperatingRegime: { domain: "text_sensor", name: "Curve operating regime", optional: true },
    curveCapacityMode: { domain: "text_sensor", name: "Curve capacity mode", optional: true },
    hpCapacity: { domain: "sensor", name: "HP capacity (W)", optional: true },
    hpDeficit: { domain: "sensor", name: "HP deficit (W)", optional: true },
    phouseHouse: { domain: "sensor", name: "Power House – P_house", optional: true },
    phouseReq: { domain: "sensor", name: "Power House – P_req", optional: true },
    duoOptimizerReason: { domain: "text_sensor", name: "Duo optimizer reason", optional: true },
    selectedInputHoldActive: { domain: "text_sensor", name: "Selected Input Hold Active", optional: true },
    silentActive: { domain: "binary_sensor", name: "Silent active" },
    silentStatus: { domain: "text_sensor", name: "Silent status", optional: true },
    silentWindow: { domain: "text_sensor", name: "Silent window (start-end)", optional: true },
    stickyActive: { domain: "binary_sensor", name: "Sticky pump active" },
    housePower: { domain: "number", name: "Rated maximum house power" },
    houseColdTemp: { domain: "number", name: "House cold temp" },
    houseOutdoorMax: { domain: "number", name: "Maximum heating outdoor temperature" },
    phResponseProfile: { domain: "select", name: "Power House response profile" },
    phKp: { domain: "number", name: "Power House temperature reaction" },
    phComfortBelow: { domain: "number", name: "Power House comfort below setpoint" },
    phComfortAbove: { domain: "number", name: "Power House comfort above setpoint" },
    phDemandRiseTime: { domain: "number", name: "Power House demand rise time" },
    phDemandFallTime: { domain: "number", name: "Power House demand fall time" },
    lowLoadDynamicThresholds: { domain: "text_sensor", name: "Low-load dynamic thresholds", optional: true },
    lowLoadDynamicOffFactor: { domain: "number", name: "Low-load dynamic OFF factor", optional: true },
    lowLoadDynamicOnFactor: { domain: "number", name: "Low-load dynamic ON factor", optional: true },
    lowLoadMinimumHysteresis: { domain: "number", name: "Low-load minimum hysteresis", optional: true },
    lowLoadCm2ReentryBlock: { domain: "number", name: "Low-load CM2 re-entry block", optional: true },
    curveControlProfile: { domain: "select", name: "Heating Curve Control Profile" },
    heatingCurvePidKp: { domain: "number", name: "Heating Curve PID Kp", optional: true },
    heatingCurvePidKi: { domain: "number", name: "Heating Curve PID Ki", optional: true },
    heatingCurvePidKd: { domain: "number", name: "Heating Curve PID Kd", optional: true },
    curveFallbackSupply: { domain: "number", name: "Curve Fallback Tsupply (No Outside Temp)" },
    curveM20: { domain: "number", name: "Curve Tsupply @ -20°C" },
    curveM10: { domain: "number", name: "Curve Tsupply @ -10°C" },
    curve0: { domain: "number", name: "Curve Tsupply @ 0°C" },
    curve5: { domain: "number", name: "Curve Tsupply @ 5°C" },
    curve10: { domain: "number", name: "Curve Tsupply @ 10°C" },
    curve15: { domain: "number", name: "Curve Tsupply @ 15°C" },
    hp1ExcludedA: { domain: "select", name: "HP1 - Excluded compressor level A" },
    hp1ExcludedB: { domain: "select", name: "HP1 - Excluded compressor level B" },
    hp1Power: { domain: "sensor", name: "HP1 - Power Input" },
    hp1Heat: { domain: "sensor", name: "HP1 - Heat Power" },
    hp1Cooling: { domain: "sensor", name: "HP1 - Cooling Power" },
    hp1Cop: { domain: "sensor", name: "HP1 - COP" },
    hp1Compressor: { domain: "sensor", name: "HP1 compressor level", optional: true },
    hp1Freq: { domain: "sensor", name: "HP1 - Compressor frequency" },
    hp1FanSpeed: { domain: "sensor", name: "HP1 - Fan speed" },
    hp1Flow: { domain: "sensor", name: "HP1 - Flow" },
    hp1EvaporatorCoilTemp: { domain: "sensor", name: "HP1 - Evaporator coil temperature" },
    hp1InnerCoilTemp: { domain: "sensor", name: "HP1 - Inner coil temperature" },
    hp1OutsideTemp: { domain: "sensor", name: "HP1 - Outside temperature" },
    hp1CondenserPressure: { domain: "sensor", name: "HP1 - Condenser pressure" },
    hp1DischargeTemp: { domain: "sensor", name: "HP1 - Gas discharge temperature" },
    hp1EvaporatorPressure: { domain: "sensor", name: "HP1 - Evaporator pressure" },
    hp1ReturnTemp: { domain: "sensor", name: "HP1 - Gas return temperature" },
    hp1WaterIn: { domain: "sensor", name: "HP1 - Water in temperature" },
    hp1WaterOut: { domain: "sensor", name: "HP1 - Water out temperature" },
    hp1WaterInRaw: { domain: "sensor", name: "HP1 - Water in temperature raw", optional: true },
    hp1WaterOutRaw: { domain: "sensor", name: "HP1 - Water out temperature raw", optional: true },
    hp1Mode: { domain: "text_sensor", name: "HP1 - Working Mode Label" },
    hp1Failures: { domain: "text_sensor", name: "HP1 - Active Failures List" },
    hp1Defrost: { domain: "binary_sensor", name: "HP1 - Defrost" },
    hp1BottomPlate: { domain: "binary_sensor", name: "HP1 - Bottom plate heater" },
    hp1Crankcase: { domain: "binary_sensor", name: "HP1 - Crankcase heater" },
    hp1Eev: { domain: "sensor", name: "HP1 - EEV steps" },
    hp1FourWay: { domain: "binary_sensor", name: "HP1 - 4-Way valve" },
    hp2ExcludedA: { domain: "select", name: "HP2 - Excluded compressor level A", optional: true },
    hp2ExcludedB: { domain: "select", name: "HP2 - Excluded compressor level B", optional: true },
    hp2Power: { domain: "sensor", name: "HP2 - Power Input", optional: true },
    hp2Heat: { domain: "sensor", name: "HP2 - Heat Power", optional: true },
    hp2Cooling: { domain: "sensor", name: "HP2 - Cooling Power", optional: true },
    hp2Cop: { domain: "sensor", name: "HP2 - COP", optional: true },
    hp2Compressor: { domain: "sensor", name: "HP2 compressor level", optional: true },
    hp2Freq: { domain: "sensor", name: "HP2 - Compressor frequency", optional: true },
    hp2FanSpeed: { domain: "sensor", name: "HP2 - Fan speed", optional: true },
    hp2Flow: { domain: "sensor", name: "HP2 - Flow", optional: true },
    hp2EvaporatorCoilTemp: { domain: "sensor", name: "HP2 - Evaporator coil temperature", optional: true },
    hp2InnerCoilTemp: { domain: "sensor", name: "HP2 - Inner coil temperature", optional: true },
    hp2OutsideTemp: { domain: "sensor", name: "HP2 - Outside temperature", optional: true },
    hp2CondenserPressure: { domain: "sensor", name: "HP2 - Condenser pressure", optional: true },
    hp2DischargeTemp: { domain: "sensor", name: "HP2 - Gas discharge temperature", optional: true },
    hp2EvaporatorPressure: { domain: "sensor", name: "HP2 - Evaporator pressure", optional: true },
    hp2ReturnTemp: { domain: "sensor", name: "HP2 - Gas return temperature", optional: true },
    hp2WaterIn: { domain: "sensor", name: "HP2 - Water in temperature", optional: true },
    hp2WaterOut: { domain: "sensor", name: "HP2 - Water out temperature", optional: true },
    hp2WaterInRaw: { domain: "sensor", name: "HP2 - Water in temperature raw", optional: true },
    hp2WaterOutRaw: { domain: "sensor", name: "HP2 - Water out temperature raw", optional: true },
    hp2Mode: { domain: "text_sensor", name: "HP2 - Working Mode Label", optional: true },
    hp2Failures: { domain: "text_sensor", name: "HP2 - Active Failures List", optional: true },
    hp2Defrost: { domain: "binary_sensor", name: "HP2 - Defrost", optional: true },
    hp2BottomPlate: { domain: "binary_sensor", name: "HP2 - Bottom plate heater", optional: true },
    hp2Crankcase: { domain: "binary_sensor", name: "HP2 - Crankcase heater", optional: true },
    hp2Eev: { domain: "sensor", name: "HP2 - EEV steps", optional: true },
    hp2FourWay: { domain: "binary_sensor", name: "HP2 - 4-Way valve", optional: true },
    apply: { domain: "button", name: "Complete setup" },
    reset: { domain: "button", name: "Reset setup state" },
  };

  ODU_RUNTIME_FREQUENCY_HP_IDS.forEach((hpIndex) => {
    const prefix = `HP${hpIndex} - EXPERIMENTAL`;
    ENTITY_DEFS[getOduRuntimeFrequencyControlKey(hpIndex, "Enable")] = {
      domain: "switch",
      name: `${prefix} ODU runtime frequency write enable`,
      optional: true,
    };
    ENTITY_DEFS[getOduRuntimeFrequencyControlKey(hpIndex, "Load")] = {
      domain: "button",
      name: `${prefix} load ODU runtime frequency table`,
      optional: true,
    };
    ENTITY_DEFS[getOduRuntimeFrequencyControlKey(hpIndex, "Apply")] = {
      domain: "button",
      name: `${prefix} apply ODU runtime frequency table`,
      optional: true,
    };
    ENTITY_DEFS[getOduRuntimeFrequencyControlKey(hpIndex, "Status")] = {
      domain: "text_sensor",
      name: `${prefix} ODU runtime frequency status`,
      optional: true,
    };
    ODU_RUNTIME_FREQUENCY_MODES.forEach((mode) => {
      ODU_RUNTIME_FREQUENCY_LEVELS.forEach((level) => {
        ENTITY_DEFS[getOduRuntimeFrequencyValueKey(hpIndex, mode, level)] = {
          domain: "number",
          name: `${prefix} ${getOduRuntimeFrequencyModeLabel(mode)} F${level} runtime Hz`,
          optional: true,
        };
      });
    });
  });

  const APP_VIEWS = [
    { id: "overview", label: "Overzicht" },
    { id: "energy", label: "Energie" },
    { id: "diagnosis", label: "Diagnose" },
    { id: "results", label: "Resultaten" },
    { id: "settings", label: "Instellingen" },
  ];
  const APP_VIEW_IDS = new Set(APP_VIEWS.map((view) => view.id));
  const SETTINGS_GROUPS = [
    { id: "installation", label: "Installatie" },
    { id: "heating", label: "Verwarmen" },
    { id: "cooling", label: "Koelen" },
    { id: "integrations", label: "Bronnen / integraties" },
    { id: "service", label: "Service" },
    { id: "system", label: "Systeem" },
  ];
  const SETTINGS_GROUP_IDS = new Set(SETTINGS_GROUPS.map((group) => group.id));
  const HP_PANEL_CONFIGS = [
    {
      title: "HP1",
      accent: "blue",
      keys: {
        power: "hp1Power",
        heat: "hp1Heat",
        cooling: "hp1Cooling",
        cop: "hp1Cop",
        freq: "hp1Freq",
        fanSpeed: "hp1FanSpeed",
        flow: "hp1Flow",
        evaporatorCoilTemp: "hp1EvaporatorCoilTemp",
        innerCoilTemp: "hp1InnerCoilTemp",
        outsideTemp: "hp1OutsideTemp",
        condenserPressure: "hp1CondenserPressure",
        dischargeTemp: "hp1DischargeTemp",
        evaporatorPressure: "hp1EvaporatorPressure",
        returnTemp: "hp1ReturnTemp",
        waterIn: "hp1WaterIn",
        waterOut: "hp1WaterOut",
        mode: "hp1Mode",
        failures: "hp1Failures",
        defrost: "hp1Defrost",
        bottomPlate: "hp1BottomPlate",
        crankcase: "hp1Crankcase",
        eev: "hp1Eev",
        fourWay: "hp1FourWay",
      },
    },
    {
      title: "HP2",
      accent: "orange",
      keys: {
        power: "hp2Power",
        heat: "hp2Heat",
        cooling: "hp2Cooling",
        cop: "hp2Cop",
        freq: "hp2Freq",
        fanSpeed: "hp2FanSpeed",
        flow: "hp2Flow",
        evaporatorCoilTemp: "hp2EvaporatorCoilTemp",
        innerCoilTemp: "hp2InnerCoilTemp",
        outsideTemp: "hp2OutsideTemp",
        condenserPressure: "hp2CondenserPressure",
        dischargeTemp: "hp2DischargeTemp",
        evaporatorPressure: "hp2EvaporatorPressure",
        returnTemp: "hp2ReturnTemp",
        waterIn: "hp2WaterIn",
        waterOut: "hp2WaterOut",
        mode: "hp2Mode",
        failures: "hp2Failures",
        defrost: "hp2Defrost",
        bottomPlate: "hp2BottomPlate",
        crankcase: "hp2Crankcase",
        eev: "hp2Eev",
        fourWay: "hp2FourWay",
      },
    },
  ];

  const CURVE_POINTS = [
    { key: "curveM20", outdoor: -20, label: "-20°C" },
    { key: "curveM10", outdoor: -10, label: "-10°C" },
    { key: "curve0", outdoor: 0, label: "0°C" },
    { key: "curve5", outdoor: 5, label: "5°C" },
    { key: "curve10", outdoor: 10, label: "10°C" },
    { key: "curve15", outdoor: 15, label: "15°C" },
  ];

  const POWER_HOUSE_KEYS = [
    "housePower",
    "houseColdTemp",
    "houseOutdoorMax",
    "phResponseProfile",
    "phKp",
    "phComfortBelow",
    "phComfortAbove",
    "phDemandRiseTime",
    "phDemandFallTime",
  ];
  const LIMIT_KEYS = ["dayMax", "silentMax", "maxWater"];
  const FLOW_SETTING_KEYS = ["flowControlMode", "flowSetpoint", "coolingFlowSetpoint", "manualIpwm"];
  const FLOW_TUNING_KEYS = ["flowKp", "flowKi"];
  const SENSOR_CALIBRATION_KEYS = [
    "hp1WaterInOffset",
    "hp1WaterOutOffset",
    "hp2WaterInOffset",
    "hp2WaterOutOffset",
  ];
  const SENSOR_CALIBRATION_STATE_KEYS = [
    "hp1WaterInRaw",
    "hp1WaterIn",
    "hp1WaterOutRaw",
    "hp1WaterOut",
    "hp2WaterInRaw",
    "hp2WaterIn",
    "hp2WaterOutRaw",
    "hp2WaterOut",
  ];
  const INSTALLATION_MONITORING_STATE_KEYS = [
    "compressorStarts2hWarningLimit",
    "compressorStarts72hWarningLimit",
    "compressorCyclingWarning2h",
    "compressorCyclingWarning72h",
    "alternatingCompressorStartsWarning",
    "compressorCyclingAlertLatched",
    "compressorCyclingAlertAlternating",
    "compressorCyclingAlertFirstSeen",
    "compressorCyclingAlertLastSeen",
    "compressorCyclingAlertHp1Peak2h",
    "compressorCyclingAlertHp1Peak72h",
    "compressorCyclingAlertHp2Peak2h",
    "compressorCyclingAlertHp2Peak72h",
    "acknowledgeCompressorCyclingAlert",
    "hp1CompressorStarts2h",
    "hp1CompressorStarts6h",
    "hp1CompressorStarts24h",
    "hp1CompressorStarts72h",
    "hp1CompressorLastStartAge",
    "hp2CompressorStarts2h",
    "hp2CompressorStarts6h",
    "hp2CompressorStarts24h",
    "hp2CompressorStarts72h",
    "hp2CompressorLastStartAge",
    "lowflowFaultActive",
    "flowMismatch",
    "cicPollingEnabled",
    "cicDataStale",
    "otEnabled",
    "otLinkProblem",
    "hp1Failures",
    "hp2Failures",
  ];
  const INSTALLATION_MONITORING_OVERVIEW_KEYS = [
    "compressorCyclingWarning2h",
    "compressorCyclingWarning72h",
    "alternatingCompressorStartsWarning",
    "compressorCyclingAlertLatched",
    "lowflowFaultActive",
    "flowMismatch",
    "cicPollingEnabled",
    "cicDataStale",
    "otEnabled",
    "otLinkProblem",
    "hp1Failures",
    "hp2Failures",
  ];
  const COMMISSIONING_STATE_KEYS = [
    "commissioningStatus",
    "cm100Active",
    "commissioningCm100Start",
    "commissioningCm100Stop",
    "boilerPowerTestStart",
    "boilerPowerTestAbort",
    "boilerPowerTestApply",
    "boilerPowerTestResult",
    "boilerPowerTestActive",
    "boilerPowerTestStatus",
    "boilerHeatPower",
    "flowAutotuneStart",
    "flowAutotuneAbort",
    "flowAutotuneApply",
    "flowAutotuneStatus",
    "flowKpSuggested",
    "flowKiSuggested",
    "airPurgeStart",
    "airPurgeAbort",
    "airPurgeReturnToAuto",
    "airPurgeActive",
    "airPurgeStatus",
    "airPurgeRemaining",
    "airPurgePhase",
    "airPurgeTargetIpwm",
    "manualFlowStart",
    "manualFlowAbort",
    "manualFlowApplyHeating",
    "manualFlowApplyCooling",
    "manualFlowActive",
    "manualFlowStatus",
    "manualFlowSetpoint",
    "manualFlowTargetIpwm",
    "manualHpStart",
    "manualHpAbort",
    "manualHpActive",
    "manualHpStatus",
    "manualHpGuardStatus",
    "manualHp1Mode",
    "manualHp2Mode",
    "manualHp1Level",
    "manualHp2Level",
    "hpWaterCalibrationStart",
    "hpWaterCalibrationAbort",
    "hpWaterCalibrationApply",
    "hpWaterCalibrationActive",
    "hpWaterCalibrationStatus",
    "hpWaterCalibrationRemaining",
    "hpWaterCalibrationPhase",
    "hpWaterCalibrationSpread",
    "hpWaterCalibrationSupplyDelta",
    "hpWaterCalibrationStableProgress",
    "hpWaterCalibrationStableRequired",
    "hpWaterCalibrationResultReference",
    "hpWaterCalibrationResultSpreadBefore",
    "hpWaterCalibrationResultExpectedSpread",
    "hpWaterCalibrationResultHp1InRawAvg",
    "hpWaterCalibrationResultHp1OutRawAvg",
    "hpWaterCalibrationResultHp2InRawAvg",
    "hpWaterCalibrationResultHp2OutRawAvg",
    ...SENSOR_CALIBRATION_STATE_KEYS,
    "hp1WaterInOffsetSuggested",
    "hp1WaterOutOffsetSuggested",
    "hp2WaterInOffsetSuggested",
    "hp2WaterOutOffsetSuggested",
    "flowSelected",
    "hp1Compressor",
    "hp1Freq",
    "hp1Failures",
    "hp2Compressor",
    "hp2Freq",
    "hp2Failures",
    "hp1Mode",
    "hp2Mode",
  ];
  const CIC_COMPATIBILITY_KEYS = ["cicCompatibilityMode"];
  const OPENTHERM_SETTING_KEYS = ["otEnabled", "otLinkProblem"];
  const CIC_POLLING_SETTING_KEYS = ["cicPollingEnabled", "cicFeedUrl", "cicDataStale"];
  const OPENTHERM_DIAGNOSTIC_KEYS = [
    "otThermostatChEnable",
    "otThermostatCoolingEnable",
    "otControlSetpoint",
    "otRoomSetpoint",
    "otRoomTemp",
  ];
  const CIC_POLLING_DIAGNOSTIC_KEYS = [
    "cicJsonFeedOk",
    "cicWaterSupplyTemp",
    "cicControlSetpoint",
    "cicRoomSetpoint",
    "cicRoomTemp",
    "cicFlowrate",
    "cicLastSuccessAge",
    "cicChEnabled",
    "cicCoolingEnabled",
  ];
  const SENSOR_SELECTION_KEYS = [
    "waterSupplySource",
    "localWaterSupplyTempSource",
    "flowSource",
    "qFlowSource",
    "outdoorUnitFlowMode",
    "outsideTempSource",
    "roomTempSource",
    "roomSetpointSource",
    "heatingEnableSource",
    "coolingEnableSource",
  ];
  const SENSOR_SELECTION_STATE_KEYS = [
    "supplyTemp",
    "waterSupplyTempEsp",
    "waterSupplyTempDs18b20",
    "waterSupplyTempHa",
    "waterSupplyTempHaValid",
    "flowSelected",
    "flowLocal",
    "controllerFlow",
    "hp1Flow",
    "hp2Flow",
    "outsideTempSelected",
    "outsideTempLocalAggregated",
    "outsideTempHa",
    "outsideTempHaValid",
    "roomTemp",
    "roomTempEffectiveSource",
    "roomTempHa",
    "roomTempHaValid",
    "roomSetpoint",
    "roomSetpointEffectiveSource",
    "roomSetpointHa",
    "roomSetpointHaValid",
    "heatingEnableSelected",
    "heatingEnableValid",
    "heatingBlockedByThermostat",
    "heatingEnableEffectiveSource",
    "otThermostatChEnable",
    "otThermostatStatusValid",
    "cicChEnabled",
    "cicChEnableValid",
    "heatingEnableHa",
    "heatingEnableHaValid",
    "coolingEnableSelected",
    "coolingEnableEffectiveSource",
    "coolingEnableHa",
    "coolingEnableHaValid",
  ];
  const QUICK_START_FLOW_SOURCE_KEYS = [
    "hardwareProfileText",
    "hpGeneration",
    "flowSource",
    "qFlowSource",
    "cicPollingEnabled",
    "cicFeedUrl",
    "cicJsonFeedOk",
    "cicDataStale",
    "cicFlowrate",
    "controllerFlow",
    "flowSelected",
    "flowLocal",
    "hp1Flow",
    "hp2Flow",
    "commissioningCm100Start",
    "commissioningCm100Stop",
    "commissioningStatus",
    "cm100Active",
    "quickFlowTest",
  ];
  const QUICK_START_THERMOSTAT_SOURCE_KEYS = [
    "hardwareProfileText",
    "roomTempSource",
    "roomSetpointSource",
    "roomTemp",
    "roomSetpoint",
    "roomTempEffectiveSource",
    "roomSetpointEffectiveSource",
    "otEnabled",
    "otLinkProblem",
    "otRoomTemp",
    "otRoomSetpoint",
    "cicPollingEnabled",
    "cicFeedUrl",
    "cicJsonFeedOk",
    "cicDataStale",
    "cicRoomTemp",
    "cicRoomSetpoint",
    "roomTempHa",
    "roomTempHaValid",
    "roomSetpointHa",
    "roomSetpointHaValid",
  ];
  const COOLING_SETTING_KEYS = [
    "coolingMinimumSupplyTemp",
    "coolingDemandMax",
    "coolingRestartDelta",
    "coolingRequestOnDelta",
    "coolingRequestOffDelta",
    "coolingSafetyMargin",
    "coolingWithoutDewPointMode",
    "coolingGuardMode",
    "coolingFallbackNightMinOutdoorTemp",
    "coolingFallbackMinSupplyTemp",
    "coolingEffectiveMinSupplyTemp",
  ];
  const CURVE_SETTING_KEYS = [...CURVE_POINTS.map((point) => point.key), "curveFallbackSupply", "curveControlProfile"];
  const COMPRESSOR_SETTING_KEYS = ["minRuntime", "hp1ExcludedA", "hp1ExcludedB", "hp2ExcludedA", "hp2ExcludedB"];
  const SILENT_SETTING_KEYS = ["silentStartTime", "silentEndTime", "silentMax", "dayMax"];
  const DEBUG_RECORDING_SAMPLE_INTERVAL_MS = 10000;
  const DEBUG_RECORDING_BUSY_RETRY_MS = 1000;
  const DEBUG_RECORDING_LOG_LIMIT = 120;
  const DEBUG_RECORDING_EVENT_LIMIT = 1000;
  const DEBUG_RECORDING_DURATION_OPTIONS = [
    { minutes: 15, label: "15 min" },
    { minutes: 30, label: "30 min" },
    { minutes: 60, label: "1 uur" },
  ];
  const DEBUG_RECORDING_KEYS = [
    "projectVersionText",
    "releaseChannelText",
    "installationTopology",
    "hardwareProfileText",
    "connectionText",
    "timeValid",
    "controlModeLabel",
    "strategy",
    "openquattEnabled",
    "manualCoolingEnable",
    "silentModeOverride",
    "outsideTempSelected",
    "roomTemp",
    "roomSetpoint",
    "supplyTemp",
    "flowSelected",
    "flowControlMode",
    "flowMode",
    "flowSetpoint",
    "coolingFlowSetpoint",
    "manualIpwm",
    "flowKp",
    "flowKi",
    "totalPower",
    "heatingPowerInput",
    "coolingPowerInput",
    "hp1Mode",
    "hp1Compressor",
    "hp1Freq",
    "hp1Flow",
    "hp1Power",
    "hp1Heat",
    "hp1Cooling",
    "hp1EvaporatorCoilTemp",
    "hp1InnerCoilTemp",
    "hp1CondenserPressure",
    "hp1EvaporatorPressure",
    "hp1WaterIn",
    "hp1WaterOut",
    "hp1Defrost",
    "hp1Failures",
    "hp2Mode",
    "hp2Compressor",
    "hp2Freq",
    "hp2Flow",
    "hp2Power",
    "hp2Heat",
    "hp2Cooling",
    "hp2EvaporatorCoilTemp",
    "hp2InnerCoilTemp",
    "hp2CondenserPressure",
    "hp2EvaporatorPressure",
    "hp2WaterIn",
    "hp2WaterOut",
    "hp2Defrost",
    "hp2Failures",
    "coolingEnableSelected",
    "coolingRequestActive",
    "coolingPermitted",
    "coolingBlockReason",
    "coolingGuardMode",
    "coolingMinimumSupplyTemp",
    "coolingSafetyMargin",
    "coolingDemandMax",
    "coolingRestartDelta",
    "coolingPidKp",
    "coolingPidKi",
    "coolingPidKd",
    "coolingDewPointSelected",
    "coolingMinimumSafeSupplyTemp",
    "coolingEffectiveMinSupplyTemp",
    "coolingSupplyTarget",
    "coolingSupplyError",
    "coolingDemandRaw",
    "coolingBaseDemandRaw",
    "coolingLimitedDemand",
    "coolingLimiterAllowedMax",
    "coolingBufferGapFiltered",
    "coolingBufferGapRate",
    "coolingProjectedGap",
    "coolingProjectionBrakeActive",
    "coolingDewGap",
    "coolingStopBufferGap",
    "coolingLimiterReasonCode",
    "coolingStopReasonCode",
    "coolingRequestReasonCode",
    "coolingRequestHp1Level",
    "coolingRequestHp2Level",
    "coolingRequestOwnerHp",
    "coolingOwnerHp",
    "coolingWaterCycleActive",
    "requestReason",
    "strategyActiveCode",
    "strategyPhaseCode",
    "strategyRequestedPower",
    "strategySupplyTarget",
    "strategyWaterLimitFactor",
    "strategyRequestActive",
    "strategyWaterTripActive",
    "strategyWaterHardTripActive",
    "curveControlProfile",
    "heatingCurvePidKp",
    "heatingCurvePidKi",
    "heatingCurvePidKd",
    "curveSupplyTarget",
    "curveDemandEffective",
    "curveDemandDiscrete",
    "curveDispatchTotalLevel",
    "curveTargetHp1Level",
    "curveTargetHp2Level",
    "curveRestartInhibit",
    "curvePhase",
    "curveOperatingRegime",
    "curveCapacityMode",
    "phouseHouse",
    "phouseReq",
    "hpCapacity",
    "hpDeficit",
    "duoOptimizerReason",
    "selectedInputHoldActive",
    "silentActive",
    "lowLoadDynamicThresholds",
    "lowLoadDynamicOffFactor",
    "lowLoadDynamicOnFactor",
    "lowLoadMinimumHysteresis",
    "lowLoadCm2ReentryBlock",
    "lowflowFaultActive",
    "flowMismatch",
    "compressorCyclingWarning2h",
    "compressorCyclingWarning72h",
    "alternatingCompressorStartsWarning",
    "cicDataStale",
    "otLinkProblem",
  ];
  const FIRMWARE_ENTITY_KEYS = ["firmwareUpdate", "firmwareUpdateChannel", "firmwareUpdateTarget", "firmwareUpdateProgress", "firmwareUpdateStatus"];
  const FIRMWARE_TEST_ENTITY_KEYS = ["firmwareTestOtaUrl", "firmwareTestOtaMd5Url", "installFirmwareTestOta"];
  const FIRMWARE_MODAL_KEYS = [...FIRMWARE_ENTITY_KEYS, ...FIRMWARE_TEST_ENTITY_KEYS, "installFirmwareUpdateTarget", "projectVersionText", "releaseChannelText", "installationTopology", "hardwareProfileText", "connectionText"];
  const TOPOLOGY_HINT_KEYS = ["hp2ExcludedA", "hp2ExcludedB", "hp2Power", "hp2WaterOut"];
  const HEADER_ENTITY_KEYS = [
    "status",
    "uptime",
    "uptimeReadable",
    "timeNowHhmm",
    "timeValid",
    "ipAddress",
    "wifiSsid",
    "wifiSignal",
    "installationTopology",
    "hardwareProfileText",
    "connectionText",
    "hpGeneration",
    "projectVersionText",
    "releaseChannelText",
    "espInternalTemp",
  ];
  const OVERVIEW_KEYS = [
    "strategy",
    "openquattEnabled",
    "boilerCvAssistEnabled",
    "openquattResumeAt",
    "manualCoolingEnable",
    "silentModeOverride",
    "coolingEnableSelected",
    "coolingRequestActive",
    "coolingPermitted",
    "coolingBlockReason",
    "coolingGuardMode",
    "coolingDewPointSelected",
    "coolingMinimumSafeSupplyTemp",
    "coolingEffectiveMinSupplyTemp",
    "coolingFallbackNightMinOutdoorTemp",
    "coolingFallbackMinSupplyTemp",
    "coolingSupplyTarget",
    "coolingSupplyError",
    "coolingDemandRaw",
    "controlModeLabel",
    "flowMode",
    "totalPower",
    "heatingPowerInput",
    "coolingPowerInput",
    "totalCop",
    "totalEer",
    "totalHeat",
    "totalCoolingPower",
    "strategyRequestedPower",
    "phouseHouse",
    "phouseReq",
    "hpCapacity",
    "boilerActive",
    "boilerHeatPower",
    "systemHeatPower",
    "electricalEnergyDaily",
    "electricalEnergyCumulative",
    "heatingElectricalEnergyDaily",
    "heatingElectricalEnergyCumulative",
    "coolingElectricalEnergyDaily",
    "coolingElectricalEnergyCumulative",
    "heatpumpThermalEnergyDaily",
    "heatpumpThermalEnergyCumulative",
    "heatpumpCoolingEnergyDaily",
    "heatpumpCoolingEnergyCumulative",
    "heatpumpCopDaily",
    "heatpumpCopCumulative",
    "heatpumpEerDaily",
    "heatpumpEerCumulative",
    "boilerThermalEnergyDaily",
    "boilerThermalEnergyCumulative",
    "systemThermalEnergyDaily",
    "systemThermalEnergyCumulative",
    "lifetimeEnergyHistoryEnabled",
    "lifetimeEnergyHourRetention",
    "lifetimeEnergyHistoryAvailable",
    "lifetimeEnergyHistoryOldest",
    "lifetimeEnergyHistoryNewest",
    "lifetimeEnergyHistoryLastWrite",
    "lifetimeEnergyHistorySize",
    "lifetimeEnergyHistoryWrites",
    "flowSelected",
    "outsideTempSelected",
    "roomTemp",
    "roomSetpoint",
    "supplyTemp",
    "curveSupplyTarget",
    "silentActive",
    "stickyActive",
    "hp1Power",
    "hp1Heat",
    "hp1Cooling",
    "hp1Cop",
    "hp1Compressor",
    "hp1Freq",
    "hp1FanSpeed",
    "hp1Flow",
    "hp1EvaporatorCoilTemp",
    "hp1InnerCoilTemp",
    "hp1OutsideTemp",
    "hp1CondenserPressure",
    "hp1DischargeTemp",
    "hp1EvaporatorPressure",
    "hp1ReturnTemp",
    "hp1WaterIn",
    "hp1WaterOut",
    "hp1Mode",
    "hp1Failures",
    "hp1Defrost",
    "hp1BottomPlate",
    "hp1Crankcase",
    "hp1Eev",
    "hp1FourWay",
    "hp2Power",
    "hp2Heat",
    "hp2Cooling",
    "hp2Cop",
    "hp2Compressor",
    "hp2Freq",
    "hp2FanSpeed",
    "hp2Flow",
    "hp2EvaporatorCoilTemp",
    "hp2InnerCoilTemp",
    "hp2OutsideTemp",
    "hp2CondenserPressure",
    "hp2DischargeTemp",
    "hp2EvaporatorPressure",
    "hp2ReturnTemp",
    "hp2WaterIn",
    "hp2WaterOut",
    "hp2Mode",
    "hp2Failures",
    "hp2Defrost",
    "hp2BottomPlate",
    "hp2Crankcase",
    "hp2Eev",
    "hp2FourWay",
  ];
  const FAST_OVERVIEW_KEYS = [
    "strategy",
    "openquattEnabled",
    "boilerCvAssistEnabled",
    "openquattResumeAt",
    "manualCoolingEnable",
    "trendHistoryEnabled",
    "trendHistoryFlashEnabled",
    "coolingPermitted",
    "coolingRequestActive",
    "coolingBlockReason",
    "controlModeLabel",
    "flowMode",
    "flowSelected",
    "outsideTempSelected",
    "roomTemp",
    "roomSetpoint",
    "supplyTemp",
    "curveSupplyTarget",
    "silentActive",
    "stickyActive",
    "totalPower",
    "heatingPowerInput",
    "coolingPowerInput",
    "totalHeat",
    "totalCoolingPower",
    "totalCop",
    "totalEer",
    "strategyRequestedPower",
    "phouseReq",
    "hpCapacity",
    "boilerActive",
    "boilerHeatPower",
    "systemHeatPower",
    "silentModeOverride",
    "hp1Power",
    "hp1Heat",
    "hp1Cooling",
    "hp1Cop",
    "hp1Compressor",
    "hp1Freq",
    "hp1FanSpeed",
    "hp1Mode",
    "hp1Flow",
    "hp1EvaporatorCoilTemp",
    "hp1InnerCoilTemp",
    "hp1OutsideTemp",
    "hp1CondenserPressure",
    "hp1DischargeTemp",
    "hp1EvaporatorPressure",
    "hp1ReturnTemp",
    "hp1WaterIn",
    "hp1WaterOut",
    "hp1Defrost",
    "hp1BottomPlate",
    "hp1Crankcase",
    "hp1Eev",
    "hp1FourWay",
    "hp2Power",
    "hp2Heat",
    "hp2Cooling",
    "hp2Cop",
    "hp2Compressor",
    "hp2Freq",
    "hp2FanSpeed",
    "hp2Mode",
    "hp2Flow",
    "hp2EvaporatorCoilTemp",
    "hp2InnerCoilTemp",
    "hp2OutsideTemp",
    "hp2CondenserPressure",
    "hp2DischargeTemp",
    "hp2EvaporatorPressure",
    "hp2ReturnTemp",
    "hp2WaterIn",
    "hp2WaterOut",
    "hp2Defrost",
    "hp2BottomPlate",
    "hp2Crankcase",
    "hp2Eev",
    "hp2FourWay",
    ...INSTALLATION_MONITORING_OVERVIEW_KEYS,
  ];
  const OVERVIEW_METADATA_KEYS = [
    "hpGeneration",
    "boilerCvAssistEnabled",
    "boilerRatedHeatPower",
    "strategy",
    ...POWER_HOUSE_KEYS,
    ...CURVE_SETTING_KEYS,
    ...FLOW_SETTING_KEYS,
    "maxWater",
    ...SILENT_SETTING_KEYS,
    ...QUICK_START_FLOW_SOURCE_KEYS,
    ...QUICK_START_THERMOSTAT_SOURCE_KEYS,
    "coolingDewPointSelected",
    "coolingMinimumSafeSupplyTemp",
    "coolingEffectiveMinSupplyTemp",
    "coolingFallbackNightMinOutdoorTemp",
    "coolingFallbackMinSupplyTemp",
    "coolingSupplyTarget",
    "coolingSupplyError",
    "coolingDemandRaw",
    "totalPower",
    "heatingPowerInput",
    "coolingPowerInput",
    "totalHeat",
    "totalCoolingPower",
    "strategyRequestedPower",
    "phouseHouse",
    "phouseReq",
    "hpCapacity",
    "boilerActive",
    "boilerHeatPower",
    "systemHeatPower",
    "flowSelected",
    "roomTemp",
    "roomSetpoint",
    "supplyTemp",
    "curveSupplyTarget",
    "hp1Power",
    "hp1Heat",
    "hp1Cooling",
    "hp1Freq",
    "hp1FanSpeed",
    "hp1Flow",
    "hp1EvaporatorCoilTemp",
    "hp1InnerCoilTemp",
    "hp1OutsideTemp",
    "hp1CondenserPressure",
    "hp1DischargeTemp",
    "hp1EvaporatorPressure",
    "hp1ReturnTemp",
    "hp1WaterIn",
    "hp1WaterOut",
    "hp2Power",
    "hp2Heat",
    "hp2Cooling",
    "hp2Freq",
    "hp2FanSpeed",
    "hp2Flow",
    "hp2EvaporatorCoilTemp",
    "hp2InnerCoilTemp",
    "hp2OutsideTemp",
    "hp2CondenserPressure",
    "hp2DischargeTemp",
    "hp2EvaporatorPressure",
    "hp2ReturnTemp",
    "hp2WaterIn",
    "hp2WaterOut",
  ];
  const OVERVIEW_ENERGY_COLUMN_CONFIGS = [
    {
      label: "Nu",
      tone: "blue",
      categories: [
        {
          title: "Verwarmen",
          tone: "orange",
          groups: [
            { title: "Warmtepomp", rows: [["Elektrisch vermogen", "heatingPowerInput"], ["Warmteafgifte", "totalHeat"], ["COP", "totalCop"]] },
            { title: "CV-ketel", rows: [["Warmteafgifte", "boilerHeatPower"]] },
            { title: "Systeem", rows: [["Warmteafgifte", "systemHeatPower"]] },
          ],
        },
        {
          title: "Koelen",
          tone: "blue",
          groups: [
            { title: "Warmtepomp", rows: [["Elektrisch vermogen", "coolingPowerInput"], ["Koelafgifte", "totalCoolingPower"], ["COP (EER)", "totalEer"]] },
          ],
        },
      ],
    },
    {
      label: "Vandaag",
      tone: "orange",
      categories: [
        {
          title: "Verwarmen",
          tone: "orange",
          groups: [
            { title: "Warmtepomp", rows: [["Elektriciteit", "heatingElectricalEnergyDaily"], ["Warmte", "heatpumpThermalEnergyDaily"], ["COP", "heatpumpCopDaily"]] },
            { title: "CV-ketel", rows: [["Warmte", "boilerThermalEnergyDaily"]] },
            { title: "Systeem", rows: [["Warmte", "systemThermalEnergyDaily"]] },
          ],
        },
        {
          title: "Koelen",
          tone: "blue",
          groups: [
            { title: "Warmtepomp", rows: [["Elektriciteit", "coolingElectricalEnergyDaily"], ["Koeling", "heatpumpCoolingEnergyDaily"], ["COP (EER)", "heatpumpEerDaily"]] },
          ],
        },
      ],
    },
    {
      label: "Cumulatief",
      tone: "green",
      categories: [
        {
          title: "Verwarmen",
          tone: "orange",
          groups: [
            { title: "Warmtepomp", rows: [["Elektriciteit", "heatingElectricalEnergyCumulative"], ["Warmte", "heatpumpThermalEnergyCumulative"], ["COP", "heatpumpCopCumulative"]] },
            { title: "CV-ketel", rows: [["Warmte", "boilerThermalEnergyCumulative"]] },
            { title: "Systeem", rows: [["Warmte", "systemThermalEnergyCumulative"]] },
          ],
        },
        {
          title: "Koelen",
          tone: "blue",
          groups: [
            { title: "Warmtepomp", rows: [["Elektriciteit", "coolingElectricalEnergyCumulative"], ["Koeling", "heatpumpCoolingEnergyCumulative"], ["COP (EER)", "heatpumpEerCumulative"]] },
          ],
        },
      ],
    },
  ];
  const SETTINGS_KEYS = [
    "strategy",
    "installationTopology",
    "hpGeneration",
    "openquattEnabled",
    "boilerCvAssistEnabled",
    "boilerRatedHeatPower",
    ...COMMISSIONING_STATE_KEYS,
    "manualCoolingEnable",
    "silentModeOverride",
    "trendHistoryEnabled",
    "trendHistoryFlashEnabled",
    "trendHistoryFlush",
    "webServerLogHistoryEnabled",
    "trendHistoryFlashAvailable",
    "trendHistoryFlashOldest",
    "trendHistoryFlashNewest",
    "trendHistoryFlashLastFlush",
    "trendHistoryFlashSize",
    "trendHistoryFlashWrites",
    "lifetimeEnergyHistoryEnabled",
    "lifetimeEnergyHourRetention",
    "lifetimeEnergyHistoryCapture",
    "lifetimeEnergyHistoryClear",
    "lifetimeEnergyHistoryAvailable",
    "lifetimeEnergyHistoryOldest",
    "lifetimeEnergyHistoryNewest",
    "lifetimeEnergyHistoryLastWrite",
    "lifetimeEnergyHistorySize",
    "lifetimeEnergyHistoryWrites",
    ...CIC_COMPATIBILITY_KEYS,
    ...OPENTHERM_SETTING_KEYS,
    ...OPENTHERM_DIAGNOSTIC_KEYS,
    ...CIC_POLLING_SETTING_KEYS,
    ...CIC_POLLING_DIAGNOSTIC_KEYS,
    ...SENSOR_SELECTION_KEYS,
    ...SENSOR_SELECTION_STATE_KEYS,
    ...FLOW_SETTING_KEYS,
    ...FLOW_TUNING_KEYS,
    ...SENSOR_CALIBRATION_KEYS,
    ...SENSOR_CALIBRATION_STATE_KEYS,
    ...INSTALLATION_MONITORING_STATE_KEYS,
    ...COOLING_SETTING_KEYS,
    ...LIMIT_KEYS,
    ...POWER_HOUSE_KEYS,
    ...CURVE_SETTING_KEYS,
    ...COMPRESSOR_SETTING_KEYS,
    ...SILENT_SETTING_KEYS,
    ...ODU_RUNTIME_FREQUENCY_KEYS,
  ];
  const SETTINGS_BACKUP_WRITABLE_DOMAINS = new Set(["number", "select", "switch", "text", "time", "datetime"]);
  const SETTINGS_BACKUP_EXPECTED_EXTRA_KEYS = new Set(["setupComplete", "openquattResumeAt", "firmwareUpdateChannel"]);
  const SETTINGS_BACKUP_EXCLUDED_KEYS = new Set([
    "installationTopology",
    ...COMMISSIONING_STATE_KEYS,
    ...ODU_RUNTIME_FREQUENCY_KEYS,
    "trendHistoryFlashAvailable",
    "trendHistoryFlashOldest",
    "trendHistoryFlashNewest",
    "trendHistoryFlashLastFlush",
    "trendHistoryFlashSize",
    "trendHistoryFlashWrites",
    "lifetimeEnergyHistoryAvailable",
    "lifetimeEnergyHistoryOldest",
    "lifetimeEnergyHistoryNewest",
    "lifetimeEnergyHistoryLastWrite",
    "lifetimeEnergyHistorySize",
    "lifetimeEnergyHistoryWrites",
    "cicDataStale",
    "otLinkProblem",
    "coolingGuardMode",
    "coolingFallbackNightMinOutdoorTemp",
    "coolingFallbackMinSupplyTemp",
    "coolingEffectiveMinSupplyTemp",
  ]);
  // Keep this aligned with persisted UI settings. The build checks that new
  // writable settings are backed up or explicitly excluded above.
  const SETTINGS_BACKUP_SECTIONS = [
    {
      id: "installation",
      label: "Installatie",
      keys: [
        "setupComplete",
        "hpGeneration",
        "boilerCvAssistEnabled",
        "boilerRatedHeatPower",
      ],
    },
    {
      id: "operation",
      label: "Bediening",
      keys: [
        "strategy",
        "openquattEnabled",
        "manualCoolingEnable",
        "silentModeOverride",
        "openquattResumeAt",
      ],
    },
    {
      id: "integrations",
      label: "Integraties",
      keys: [
        "otEnabled",
        "cicPollingEnabled",
        "cicFeedUrl",
        "cicCompatibilityMode",
      ],
    },
    {
      id: "sensor_sources",
      label: "Sensorbronnen",
      keys: [
        "waterSupplySource",
        "localWaterSupplyTempSource",
        "flowSource",
        "qFlowSource",
        "outdoorUnitFlowMode",
        "outsideTempSource",
        "roomTempSource",
        "roomSetpointSource",
        "heatingEnableSource",
        "coolingEnableSource",
        ...SENSOR_CALIBRATION_KEYS,
      ],
    },
    {
      id: "comfort",
      label: "Comfort",
      keys: [
        "silentStartTime",
        "silentEndTime",
        "dayMax",
        "silentMax",
        "maxWater",
      ],
    },
    {
      id: "heatingCurve",
      label: "Stooklijn",
      keys: [
        "curveControlProfile",
        "curveFallbackSupply",
        ...CURVE_POINTS.map((point) => point.key),
      ],
    },
    {
      id: "powerHouse",
      label: "Power House",
      keys: [
        "housePower",
        "houseColdTemp",
        "houseOutdoorMax",
        "phResponseProfile",
        "phKp",
        "phComfortBelow",
        "phComfortAbove",
        "phDemandRiseTime",
        "phDemandFallTime",
      ],
    },
    {
      id: "flow",
      label: "Flow",
      keys: ["flowControlMode", "flowSetpoint", "coolingFlowSetpoint", "manualIpwm", "flowKp", "flowKi"],
    },
    {
      id: "cooling",
      label: "Koeling",
      keys: [
        "coolingMinimumSupplyTemp",
        "coolingDemandMax",
        "coolingRestartDelta",
        "coolingRequestOnDelta",
        "coolingRequestOffDelta",
        "coolingSafetyMargin",
        "coolingWithoutDewPointMode",
      ],
    },
    {
      id: "compressor",
      label: "Compressor",
      keys: ["minRuntime", "compressorStarts2hWarningLimit", "compressorStarts72hWarningLimit", "hp1ExcludedA", "hp1ExcludedB", "hp2ExcludedA", "hp2ExcludedB"],
    },
    {
      id: "system",
      label: "Systeem",
      keys: [
        "trendHistoryEnabled",
        "trendHistoryFlashEnabled",
        "lifetimeEnergyHistoryEnabled",
        "lifetimeEnergyHourRetention",
        "webServerLogHistoryEnabled",
        "firmwareUpdateChannel",
      ],
    },
  ];
  const SETTINGS_BACKUP_SCHEMA_VERSION = 1;
  const SETTINGS_BACKUP_KEYS = [...new Set(SETTINGS_BACKUP_SECTIONS.flatMap((section) => section.keys))];
  const SETTINGS_BACKUP_KEY_SET = new Set(SETTINGS_BACKUP_KEYS);
  const FAST_POLL_INTERVAL_MS = 5000;
  const BULK_POLL_INTERVAL_MS = 30000;
  const STATIC_POLL_INTERVAL_MS = 60000;
  const CONNECTIVITY_PROBE_TIMEOUT_MS = 1500;
  const CONNECTIVITY_PROBE_SUCCESS_TTL_MS = 30000;
  const SUPPLEMENTARY_STATUS_REFRESH_INTERVAL_MS = 30000;
  const LOGIN_MODAL_AUTH_STATUS_REFRESH_INTERVAL_MS = 1000;
  const HIDDEN_POLL_INTERVAL_MS = 30000;
  const POLL_JITTER_MIN_MS = 250;
  const POLL_JITTER_MAX_MS = 750;
  const FLOW_DASH_CYCLE_PX = 22;
  const FLOW_OFFSET_PX_PER_SEC = FLOW_DASH_CYCLE_PX / 1.7;
  const FAN_ROTATION_DEG_PER_SEC = 360 / 3.2;
const OPENQUATT_RESUME_CLEAR_VALUE = "2000-01-01 00:00:00";
