# ==============================================================================
# OpenQuatt - Electropaultje Heatpump Controller Q-edition / Duo / Wi-Fi
# ==============================================================================
substitutions:
  <<: !include ../../openquatt/oq_substitutions_common.yaml
  <<: !include ../../openquatt/topology/duo.yaml
  oq_topology_build_flag: "-DOQ_TOPOLOGY_DUO=1"
  main_release_manifest_url: "https://github.com/jeroen85/OpenQuatt/releases/latest/download/openquatt-heatpump-controller-q-duo-wifi-ota.manifest.json"
  dev_release_manifest_url: "https://github.com/jeroen85/OpenQuatt/releases/download/dev-latest/openquatt-heatpump-controller-q-duo-wifi-ota.manifest.json"
  release_manifest_url: "https://github.com/jeroen85/OpenQuatt/releases/latest/download/openquatt-heatpump-controller-q-duo-wifi-ota.manifest.json"

esphome:
  build_path: ../../../.esphome/build/heatpump_controller_q_duo_wifi

packages:
  openquatt_profile_heatpump_controller_q: !include ../../openquatt/profiles/heatpump_controller_q.yaml
  openquatt_base_common: !include ../../openquatt/base/common.yaml
  openquatt_connection_wifi: !include ../../openquatt/connection/wifi.yaml
  <<: !include ../../openquatt/oq_packages_common.yaml
  <<: !include ../../openquatt/topology/duo_packages.yaml
