# ==============================================================================
# OpenQuatt - Heatpump Controller Q PSRAM
# ==============================================================================
# Enables the 8MB PSRAM present on the ESP32-S3R8 controller board.
# ==============================================================================

psram:
  mode: octal
  speed: 80MHz
  ignore_not_found: false

sensor:
  - platform: debug
    psram:
      name: "PSRAM Free"
      icon: mdi:memory
      entity_category: diagnostic
      disabled_by_default: true
      accuracy_decimals: 0
      web_server:
        sorting_group_id: oq_system_diagnostics
