name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  validate-and-compile:
    uses: ./.github/workflows/esphome-build.yml
    with:
      artifact_suffix: firmware-${{ github.sha }}
      include_firmware_bin: true
