# ==============================================================================
# OpenQuatt - Local Sensors (on-device)
# ==============================================================================
#
# Goal:
#   Host direct on-device physical sensors.
#
# Current scope:
#   - DS18B20 local water supply temperature (1-Wire on configured GPIO)
#
# ==============================================================================

one_wire:
  - platform: gpio
    pin: ${ds18b20_pin}

sensor:
  - platform: dallas_temp
    id: water_supply_temp_esp
    name: "Water Supply Temp"
    icon: mdi:thermometer
    unit_of_measurement: "°C"
    device_class: temperature
    state_class: measurement
    accuracy_decimals: 2
    update_interval: 5s
    web_server:
      sorting_group_id: oq_temperatures
