# ==============================================================================
# OpenQuatt - Topology Adapter (duo)
# ==============================================================================
# Exposes setup-agnostic IDs used by shared control packages.
# Duo variant maps these IDs to real HP2 entities and dual-actuator writes.
# ==============================================================================

sensor:
  - platform: template
    id: oq_topology_outside_secondary
    internal: true
    update_interval: 5s
    lambda: |-
      return id(hp2_outside_temp).state;

  - platform: template
    id: oq_topology_flow_secondary
    internal: true
    update_interval: 1s
    lambda: |-
      return id(hp2_flow).state;

  - platform: template
    id: oq_topology_supply_fallback_temp
    internal: true
    update_interval: 5s
    lambda: |-
      return id(hp2_water_out_temp).state;

  - platform: template
    id: oq_topology_boiler_upstream_outlet_temp
    internal: true
    update_interval: 5s
    lambda: |-
      return id(hp2_water_out_temp).state;

  - platform: template
    id: oq_topology_secondary_working_mode
    internal: true
    update_interval: 5s
    lambda: |-
      return id(hp2_working_mode).state;

  - platform: template
    id: oq_topology_secondary_last_applied_level
    internal: true
    update_interval: 5s
    lambda: |-
      return (float) id(hp2_last_applied_level);

script:
  - id: oq_topology_set_low_noise_all
    parameters:
      enable: bool
    then:
      - lambda: |-
          const char *opt = enable ? "On" : "Off";
          auto apply_select = [&](auto *sel) {
            if (sel == nullptr) return;
            if (!sel->has_state() || sel->current_option() != opt) {
              auto c = sel->make_call();
              c.set_option(opt);
              c.perform();
            }
          };
          apply_select(id(hp1_low_noise_mode));
          apply_select(id(hp2_low_noise_mode));

  - id: oq_topology_set_pump_mode_all
    parameters:
      enable: bool
    then:
      - lambda: |-
          const char *opt = enable ? "On" : "Off";
          auto apply_select = [&](auto *sel) {
            if (sel == nullptr) return;
            if (!sel->has_state() || sel->current_option() != opt) {
              auto c = sel->make_call();
              c.set_option(opt);
              c.perform();
            }
          };
          apply_select(id(hp1_set_pump_mode));
          apply_select(id(hp2_set_pump_mode));

  - id: oq_topology_set_pump_pwm_all
    parameters:
      pwm: float
    then:
      - lambda: |-
          auto apply_number = [&](auto *num) {
            if (num == nullptr) return;
            const float cur = num->state;
            if (isnan(cur) || fabsf(cur - pwm) > 1.0f) {
              auto c = num->make_call();
              c.set_value(pwm);
              c.perform();
            }
          };
          apply_number(id(hp1_pump_speed));
          apply_number(id(hp2_pump_speed));
